### DISCUSSION TITLE
Gitpod.io online IDE integration

### DISCUSSION THREAD

**Discussion by freiondrej-economia** [rectorphp/rector#6514] [Ideas]
Hello,
I recently stumbled upon an amazing project gitpod.io, which creates ephemeral workflows with a web IDE, think ready-to-code setups.
I have no experience with it, so proper integration with Rector should be proposed by someone who knows Gitpod, but this is a minimal setup I used to get rector working:

/.gitpod.yml
```yml
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
   - init: composer install # runs during prebuild
      command: echo 'composer install'
image:
   file: .gitpod.Dockerfile
```
/.gitpod.Dockerfile
```Dockerfile
FROM php:8.0-fpm-buster

RUN apt-get update && apt-get install -y \
	# for composer
	zip \
	unzip \
	# git
	git \
	&& rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
```
I used it to create a bugfix PR for Rector-src, but the process could be even smoother with some guidelines.
This is what I did:
1) I forked rectorphp/rector-src on Github
2) I used gitpod magic url (gitpod.io/#<repoUrl>) to spin up the workspace
3) gitpod used the .gitpod.yml file (which I had to add to my forked repo, but Rector could have it there already) to start a php8 container, where I could run tests and develop the feature.
4) I pushed my branch to Github using Gitpod commandline
5) I created the PR through Github

I think encouraging developers to use this could really lower the barrier to contributing, because they practically just need to open a new browser tab and Gitpod prepares everything for them.
WDYT? Would it be good to have .gitpod.yml already in rector, so that new contributors could start coding right away?
