### ISSUE TITLE
PHPUnit Declaration must be compatible

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#1012]
I am upgrading a test suite from PHPUnit 6 to 8. A run rector over it.
My expectation was that he fixes all return types issue. But it hangs with a Fatal Error

Fatal error: Declaration of Enlight_Components_Test_TestCase::tearDown() must be compatible with PHPUnit\Framework\TestCase::tearDown(): void

**Comment by TomasVotruba** [comment]
How does Enlight_Components_Test_TestCase::tearDown() look like?

**Comment by shyim** [comment]
```php
protected function tearDown()
    {
        if ($this->databaseTester !== null) {
            if (method_exists($this, 'getTearDownOperation')) {
                $this->getDatabaseTester()->setTearDownOperation($this->getTearDownOperation());
            }
            if (method_exists($this, 'getDataSet')) {
                $this->getDatabaseTester()->setDataSet($this->getDataSet());
            }
            $this->getDatabaseTester()->onTearDown();
        }

        $this->databaseTester = null;

        set_time_limit(0);
        ini_restore('memory_limit');
    }
```

It don't have the return type void. I guess that the tool would add it :)

**Comment by TomasVotruba** [comment]
Looks good. Does it externs the test case?

**Comment by shyim** [comment]
Yea its multiple times extended from another test cases.
Code is in tests folder and not vendor

```
docker run --rm -it  -v (pwd):/project rector/rector:latest bin/rector process --level phpunit80 --config /project/rector.yaml  /project/tests
``` 

```
# rector.yaml
parameters:
  level: phpunit80
  autoload_paths:
    - '/project/autoload.php'
    - '/project/engine/Library/Enlight/Components/Test/TestCase.php'
    - '/project/engine'
    - '/project/tests'
  exclude_rectors:
    - 'Rector\PHPUnit\Rector\MethodCall\SpecificAssertContainsRector'
```

Abstract TestCase class on Github https://github.com/shopware/shopware/blob/5.5/engine/Library/Enlight/Components/Test/TestCase.php#L69
Example class using it
https://github.com/shopware/shopware/blob/4fb20a661576322704ea0d20332bdbe3c49e2ab6/tests/Functional/Components/StreamProtocolValidatorTest.php#L30
