### ISSUE TITLE
Rename MethodCall Rector

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#1210]
The current RenameMethodRector renames also the ClassMethod itself. So this functionality is unuseable when the method is deprecated.

I could make it configureable :) if wanted

**Comment by TomasVotruba** [comment]
The current renaming class method is included, because in most cases you inherit the class and the new method is preffered.

> I could make it configureable :) if wanted 

Sure :+1: 

How do you plan to do it?

**Comment by shyim** [comment]
```yaml
services:
    Rector\Rector\MethodCall\RenameMethodRector:
        disableClassMethod: true
```

Something like this :thinking:
