### ISSUE TITLE
[Nette\Utils] code quality - function calls to utils

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1276]
- level: `nette-utils-code-quality`

```yaml
services:
    # some can be done as simply as
    Rector\Rector\Function_\FunctionToStaticCallRector:
        file_get_contents: ['Nette\Utils\FileSystem', 'read']
```

## Example

```diff
-file_get_contents($file);
+Nette\Utils\FileSystem::read($file);

-json_encode($json);
+Nette\Utils\Json::encode($json);

-strpos($content, 'hi') !=== false
+Nette\Utils\Strings::contains($content, 'hi);
```

## Source

- https://www.tomasvotruba.cz/blog/2018/07/30/hidden-gems-of-php-packages-nette-utils/
- https://github.com/Symplify/Symplify/commit/891b13ff30133ad3b328e1e22e5d338e8e8104fc
