### ISSUE TITLE
Twig prepared set

### ISSUE THREAD

**Issue by greg0ire** [rectorphp/rector#137]
Since Twig [1.34.0](https://github.com/twigphp/Twig/blob/d8d888e2ae694c8057d6b0201b7b8f6f07d430cc/CHANGELOG#L116), and [2.4.0](https://github.com/twigphp/Twig/blob/d8d888e2ae694c8057d6b0201b7b8f6f07d430cc/CHANGELOG#L34), namespaces have been introduced. It would be nice to have a set to change the codebase to use namespaces.

**Comment by greg0ire** [comment]
I tried this config:

```yaml
rectors:
    Rector\Rector\Dynamic\ClassReplacerRector:
        'Twig_Extension': 'Twig\Extension\AbstractExtension'
```
on [this file](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/src/Twig/Extension/FlashMessageExtension.php#L21)

But no use statements were inserted 😕
