### ISSUE TITLE
ShouldNotHappenException... Happened -.-' in /vendor/rector/rector/packages/PHPStan/src/Rector/Assign/PHPStormVarAnnotationRector.php:54

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1407]
Excuse me for the title, but I don't know how to write a better one: I will change it once the problem will be understood better.

I receive the exception `ShouldNotHappenException` analyzing my code.

This is the stack trace I get:

```console
PHP Fatal error:  Uncaught Rector\Exception\ShouldNotHappenException in /Users/Aerendir/Documents/Path/To/My/library/vendor/rector/rector/packages/PHPStan/src/Rector/Assign/PHPStormVarAnnotationRector.php:54
Stack trace:
#0 /Users/Aerendir/Documents/Path/To/My/library/vendor/rector/rector/src/Rector/AbstractRector.php(95): Rector\PHPStan\Rector\Assign\PHPStormVarAnnotationRector->refactor(Object(PhpParser\Node\Expr\Assign))
#1 /Users/Aerendir/Documents/Path/To/My/library/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\Assign))
#2 /Users/Aerendir/Documents/Path/To/My/library/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#3 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/C in /Users/Aerendir/Documents/Path/To/My/library/vendor/rector/rector/packages/PHPStan/src/Rector/Assign/PHPStormVarAnnotationRector.php on line 54

Fatal error: Uncaught Rector\Exception\ShouldNotHappenException in /Users/Aerendir/Documents/Path/To/My/library/vendor/rector/rector/packages/PHPStan/src/Rector/Assign/PHPStormVarAnnotationRector.php:54
Stack trace:
#0 /Users/Aerendir/Documents/Path/To/My/library/vendor/rector/rector/src/Rector/AbstractRector.php(95): Rector\PHPStan\Rector\Assign\PHPStormVarAnnotationRector->refactor(Object(PhpParser\Node\Expr\Assign))
#1 /Users/Aerendir/Documents/Path/To/My/library/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\Assign))
#2 /Users/Aerendir/Documents/Path/To/My/library/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#3 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/C in /Users/Aerendir/Documents/Path/To/My/library/vendor/rector/rector/packages/PHPStan/src/Rector/Assign/PHPStormVarAnnotationRector.php on line 54
```

What should I do? What other information do you need to fix the issue?

May be related to https://github.com/rectorphp/rector/issues/1494

**Comment by TomasVotruba** [comment]
You can try running the command with `--debug`.

Also, provide the file it crashes on. There will be some code Rector doesn't understand yet

**Comment by Aerendir** [comment]
After digging a bit in the error, I found the line that caused it (using `dd($node)`).

The line that caused the error was a simple assignment, really nothing of complex:

```php
                    case 'param_name_end':
                        $param_value = '';
                        if ('"' === $chr) {
                            $state = 'quoted_param_value_start'; // This is the line that causes the error
                        } else {
                            $state = 'param_value_start';
                        }
                        break;
```

After changing it to a ternary expression, no error happens anymore:

```php
                    case 'param_name_end':
                        $param_value = '';
                        $state = '"' === $chr
                            ? 'quoted_param_value_start'
                            : $state = 'param_value_start';
```

This is really strange.

Anyway, if I can, I suggest to pass the `Node` to the `ShouldNotHappenException()` to at least print the lines where the error happen, so it is easier to debug and to provide useful information.

**Comment by Aerendir** [comment]
@TomasVotruba , I've done exactly this and the comment above is the result of my findings...

**Comment by TomasVotruba** [comment]
Great! And which rule causes this?

What command do you run Rector with?

**Comment by Aerendir** [comment]
Rule? Maybe you intend which rector? The rector is `PHPStormVarAnnotationRector`...

The command is a simple `vendor/bin/rector process src --dry-run --debug`.

The `rector.yml` file is this:

```yaml
imports:
    #- { resource: 'vendor/rector/rector/config/level/architecture/*' }
    - { resource: 'vendor/rector/rector/config/level/code-quality/*' }
    - { resource: 'vendor/rector/rector/config/level/coding-style/*' }
    - { resource: 'vendor/rector/rector/config/level/doctrine/doctrine25.yaml' }
    - { resource: 'vendor/rector/rector/config/level/phpstan/phpstan.yaml' }
    - { resource: 'vendor/rector/rector/config/level/sensio/*' }
    # Temporary disabled as throws errors
    #- { resource: 'vendor/rector/rector/config/level/symfony/symfony-code-quality.yaml' }
    - { resource: 'vendor/rector/rector/config/level/symfony/symfony-constructor-injection.yaml' }
    - { resource: 'vendor/rector/rector/config/level/symfony/symfony42.yaml' }
    # Disabled as it causes wrong changes in the code
    #- { resource: 'vendor/rector/rector/config/level/symfony/symfony-constructor-injection.yaml' }
    # Temporary disabled until https://github.com/thecodingmachine/safe/issues/116 is resolved
    - { resource: 'vendor/thecodingmachine/safe/rector-migrate.yml' }

parameters:
    php_version_features: '7.2'
    exclude_rectors:
        - 'Rector\CodeQuality\Rector\Identical\SimplifyBoolIdenticalTrueRector'
        - 'Rector\CodeQuality\Rector\Concat\JoinStringConcatRector'
        - 'Rector\CodingStyle\Rector\Identical\IdenticalFalseToBooleanNotRector'
        # This doesn't recognize the difference between classes and functions
        # Waiting the fix https://github.com/rectorphp/rector/issues/1376
        - 'Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector'

```
