### ISSUE TITLE
[RenameClassRector] Edge case - rename to class that already exists

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#1438]
Hey, it happened that i did not notice there is already class existing and renamed some other class that new name matched it as well:

Example:
```yaml
services:
    Rector\Rector\Class_\RenameClassRector:
        GlamiImage: Glami\Image
```

But there is already class `Glami\Image` existing and autoloaded via composer.

I am curious if we should cover this edge case and add check if renaming class, whether other class already exists but i am afraid that rector is not aware of existing classes, what do you think?
