### ISSUE TITLE
[Refactoring] Merge 2 classes

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1441]
```yaml
MergeClassesRector:
   A:
     -A
     -B
```

- move B to A
- include ctor dependencies and same dependencies
- rename all B usage to A
