### ISSUE TITLE
Rector just showing version and exit

### ISSUE THREAD

**Issue by soullivaneuh** [rectorphp/rector#1458]
Since v0.4 upgrade:

```
$ vendor/bin/rector process src src-dev tests --level doctrine25

Rector v0.4.12
```

And 255 return code. The `-vvv` and `--debug` flags didn't help much.

But, rector is running if I **remove** the `rector.yml` configuration file:

```yaml
parameters:
    autoload_paths:
        - 'src/autoload.php'
        - 'vendor-bin/phpunit/vendor/autoload.php'
    exclude_paths:
        - 'src/AppBundle/Composer/ScriptHandler.php'
        - 'src/Migrations/'
```

Am I missing something between 0.3 and 0.4? Didn't find any difference on the documentation.

Regards

**Comment by TomasVotruba** [comment]
Which exact line helps to remove?

**Comment by soullivaneuh** [comment]
Same issue with minimal required configuration for autoload path:

```yaml
parameters:
    autoload_paths:
        - 'src/autoload.php'
```

Content of `src/autoload.php`:

```php
<?php

declare(strict_types=1);

use Symfony\Component\Dotenv\Dotenv;

require_once __DIR__.'/../vendor/php/autoload.php';

// This part can't be load with composer directly because it cause issues with PHPUnit env var override.
(new Dotenv())->loadEnv(__DIR__.'/../.env');
```

And I have the same issue if I try to bypass my autoload:

```yaml
parameters:
    autoload_paths:
        - 'vendor/php/autoload.php'
```
