### ISSUE TITLE
[SOLID] Rector\SOLID\Rector\ClassConst\PrivatizeLocalClassConstantRector: false positive (turns constant to private that is publicly used)

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1634]
Adding the `solid` level gives me some false positive on constants : 

```diff
1) src/SomeNamespace/ContentCacheManager.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -23,7 +23,7 @@
     /**
      * @var string
      */
-    public const CMS_CACHE_PATH = 'cms';
+    private const CMS_CACHE_PATH = 'cms';

     /**
      * @var string
    ----------- end diff -----------

Applied rectors:

 * Rector\SOLID\Rector\ClassConst\PrivatizeLocalClassConstantRector
 * Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
```

Even though it is used in others classes, for example : 

```
use SomeNamespace\ContentCacheManager;

final class LanguageFinder
{
    /**
     * @var string
     */
    public const CACHE_TAG_LANGS = ContentCacheManager::CMS_CACHE_PATH . '_langs';
```

**Comment by TomasVotruba** [comment]
What exact command did you use?

**Comment by gnutix** [comment]
Sorry for the late answer! I have a composer script defined as `"rector-dry": "vendor/bin/rector --ansi process --dry-run src/ tests/",`, which is run with `composer rector-dry`.

**Comment by TomasVotruba** [comment]
I don't see a `solid` set there. Where is it?

**Comment by gnutix** [comment]
```
# rector.yaml
imports:
    # Code quality
    - { resource: 'vendor/rector/rector/config/set/celebrity/celebrity.yaml' }
    - { resource: 'vendor/rector/rector/config/set/code-quality/code-quality.yaml' }
    - { resource: 'vendor/rector/rector/config/set/coding-style/coding-style.yaml' }
    - { resource: 'vendor/rector/rector/config/set/solid/solid.yaml' }

    # Doctrine
    - { resource: 'vendor/rector/rector/config/set/doctrine/doctrine25.yaml' }

    # PHP
    - { resource: 'vendor/rector/rector/config/set/php/php52.yaml' }
    - { resource: 'vendor/rector/rector/config/set/php/php53.yaml' }
    - { resource: 'vendor/rector/rector/config/set/php/php54.yaml' }
    - { resource: 'vendor/rector/rector/config/set/php/php55.yaml' }
    - { resource: 'vendor/rector/rector/config/set/php/php56.yaml' }
    - { resource: 'vendor/rector/rector/config/set/php/php70.yaml' }
    - { resource: 'vendor/rector/rector/config/set/php/php71.yaml' }
    - { resource: 'vendor/rector/rector/config/set/php/php72.yaml' }
    - { resource: 'vendor/rector/rector/config/set/php/php73.yaml' }

    # PHPUnit
    - { resource: 'vendor/rector/rector/config/set/phpunit/phpunit60.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpunit/phpunit70.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpunit/phpunit80.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpunit/phpunit-code-quality.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpunit/phpunit-exception.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpunit/phpunit-mock.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpunit/phpunit-specific-method.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpunit/phpunit-yield-data-provider.yaml' }

    # Symfony
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony26.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony28.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony30.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony31.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony32.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony33.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony34.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony40.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony41.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony42.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony43.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony-code-quality.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony-constructor-injection.yaml' }

    # FrameworkBundle
    - { resource: 'vendor/rector/rector/config/set/sensio/framework-extra-bundle-30.yaml' }
    - { resource: 'vendor/rector/rector/config/set/sensio/framework-extra-bundle-50.yaml' }

    # Twig
    - { resource: 'vendor/rector/rector/config/set/twig/twig112.yaml' }
    - { resource: 'vendor/rector/rector/config/set/twig/twig127.yaml' }
    - { resource: 'vendor/rector/rector/config/set/twig/twig134.yaml' }
    - { resource: 'vendor/rector/rector/config/set/twig/twig140.yaml' }
    - { resource: 'vendor/rector/rector/config/set/twig/twig20.yaml' }
    - { resource: 'vendor/rector/rector/config/set/twig/twig240.yaml' }

parameters:
    kernel_class: \OurVendor\OurBundle\Tests\App\AppKernel
    autoload_paths:
        - 'vendor/bin/.phpunit/phpunit-8.1/vendor/autoload.php'
    exclude_rectors:
        # Prefer single quotes everywhere (with some escapes) than a mix (and people start using double quotes)
        - 'Rector\CodingStyle\Rector\String_\SymplifyQuoteEscapeRector'
```
