### ISSUE TITLE
Why is Rector breaking my array to one-line instead of how it is ?

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#1652]
## Question

Why does rector modify my array style ?

Before 
```php
return [
    [
        'foo' => 'bar',
    ],
    [more]
]
```
After
```php
return [['foo' => 'bar',],[more]];
```

**Comment by TomasVotruba** [comment]
We use php-parser pretty printer here, so it might be caused by it.

- What is the command line?
- What is the minimal code to reproduce it?
- Could you send failing test case?

**Comment by vasilvestre** [comment]
### Command line
`vendor/bin/rector process --hide-autoload-errors src/`
### Minimal code to reproduce it
This example above should be fine without the [more] part
### Failing test case
```yaml
parameters:
    exclude_paths:
        - "/Fixture/"
        - "/Fixtures/"
        - "/Expected/"
        - "/Source/"
        - "/tests/" # for better performance of local changes

        # autoload-buggy cases
        - "*.php.inc"
    php_version_features: '7.1'

services:
    Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector: ~
    Rector\Rector\MethodCall\RenameMethodRector:
        # class loader
        'Symfony\Component\ClassLoader\UniversalClassLoader\UniversalClassLoader':
            'registerNamespaces': 'addPrefixes'
            'registerPrefixes': 'addPrefixes'
            'registerNamespace': 'addPrefix'
            'registerPrefix': 'addPrefix'
            'getNamespaces': 'getPrefixes'
            'getNamespaceFallbacks': 'getFallbackDirs'
            'getPrefixFallbacks': 'getFallbackDirs'

        # form
        'Symfony\Component\Form\AbstractType':
            'getName': 'getBlockPrefix'
            'setDefaultOptions': 'configureOptions'
        'Symfony\Component\Form\FormTypeInterface':
            'getName': 'getBlockPrefix'
            'setDefaultOptions': 'configureOptions'
        'Symfony\Component\Form\ResolvedFormTypeInterface':
            'getName': 'getBlockPrefix'
        'Symfony\Component\Form\AbstractTypeExtension':
            'setDefaultOptions': 'configureOptions'
        'Symfony\Component\Form\Form':
            'bind': 'submit'
            'isBound': 'isSubmitted'

        # process
        'Symfony\Component\Process\Process':
            'setStdin': 'setInput'
            'getStdin': 'getInput'

        # monolog
        'Symfony\Bridge\Monolog\Logger':
            'emerg': 'emergency'
            'crit': 'critical'
            'err': 'error'
            'warn': 'warning'

        # http kernel
        'Symfony\Component\HttpKernel\Log\LoggerInterface':
            'emerg': 'emergency'
            'crit': 'critical'
            'err': 'error'
            'warn': 'warning'
        'Symfony\Component\HttpKernel\Log\NullLogger':
            'emerg': 'emergency'
            'crit': 'critical'
            'err': 'error'
            'warn': 'warning'

        # property access
        Symfony\Component\PropertyAccess\PropertyAccess:
            'getPropertyAccessor': 'createPropertyAccessor'

        # serialazer
        'Symfony\Component\Serializer\Exception\Exception': 'Symfony\Component\Serializer\Exception\ExceptionInterface'

        # translator
        'Symfony\Component\Translation\Dumper\FileDumper':
            'format': 'formatCatalogue'
        'Symfony\Component\Translation\Translator':
            'getMessages': 'getCatalogue'

        # validator
        'Symfony\Component\Validator\ConstraintViolationInterface':
            'getMessageParameters': 'getParameters'
            'getMessagePluralization': 'getPlural'
        'Symfony\Component\Validator\ConstraintViolation':
            'getMessageParameters': 'getParameters'
            'getMessagePluralization': 'getPlural'
```

**Comment by TomasVotruba** [comment]
Could you provide minimal config? It will be probably just one rule.

**Comment by vasilvestre** [comment]
> Could you provide minimal config? It will be probably just 1 rule.
> 
> Btw, why do you write so many rules manually? It's probably part of `symfonyX` set

This is my config, what do you mean by minimal config ?

I play the symfonyX rules one by one, each a separate branch. It's only the workflow of my company.. they don't really trust rector

**Comment by TomasVotruba** [comment]
> This is my config, what do you mean by minimal config ?

The minimal amount of code in config, that is causing the issue.

```
services:
    SomeService: ~
```

> It's only the workflow of my company.. they don't really trust rector

I see and understand. I'd have same approach to 3rd party project changing my code. More people have similar need: https://github.com/rectorphp/rector-ci/issues/42

How could Rector do it better so you don't have to copy every config?

**Comment by vasilvestre** [comment]
> That's way we don't focus on 20 different potential problems, just 2.
Ok I got it :
```yaml
services:
```

```php
$i = [
    [ 'i' => 'j']
];
```

> I see and understand. I'd have same approach to 3rd party project changing my code. More people have similar need: [rectorphp/rector-ci#42](https://github.com/rectorphp/rector-ci/issues/42)

I was thinking about asking for it ahah, wp !
 
> How could Rector do it better so you don't have to copy every config?

Something like --rector for cli or --rules=symfony34[listOfRector] and same thing in rector.yaml
```yaml
services:
    Symfony34: ~    <-- all sf 34 rules
    Symfony28:       <-- rector I want but with sf28 rules
        - Rector1: ~
        - Rector 2: ~
```
