### ISSUE TITLE
Use rules of a set easily

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#1654]
Instead of putting rules one by one on `rector.yaml` file in order to execute (for example) Symfony30 rule about the `RenameClassConstantRector` part.
I have to write in my file
```yaml
    Rector\Rector\Constant\RenameClassConstantRector:
        # form
        'Symfony\Component\Form\FormEvents':
            'PRE_BIND': 'PRE_SUBMIT'
            'BIND': 'SUBMIT'
            'POST_BIND': 'POST_SUBMIT'
        'Symfony\Component\Form\Extension\Core\DataTransformer':
            'ROUND_HALFEVEN': 'ROUND_HALF_EVEN'
            'ROUND_HALFUP': 'ROUND_HALF_UP'
            'ROUND_HALFDOWN': 'ROUND_HALF_DOWN'
```
An option could be 
```yaml
Symfony30: 
    Rector\Rector\Constant\RenameClassConstantRector: ~
```
