### ISSUE TITLE
[DX] Add "only" option to run only on specific files

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1669]
## Use case

I need to run rule only on files in `*/Entity/*` directory, but now I have to run it on full code base.

## Implementation

PR to ECS: https://github.com/Symplify/Symplify/pull/1537

```yaml
# rector.yaml

parameters:
    only:
        - `*/Entity/*`

services:
     RuleThatChangesOnlyEntityRector: ~
```
