### ISSUE TITLE
Strange errors at the end of Rector's execution

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1873]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | `PHP 7.3.8-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2019 09:52:12) ( NTS )` |
| Full Command   | `vendor/bin/rector --ansi process src/ tests/`  | 

## Current Behaviour 

There are two errors that repeat multiple times at the end of Rector's output.
1) :  

```
[ERROR] Could not process                                                      
         "tests/Functional/someRandomTestFile.php" file, due to:                     
         "Analyze error: "Class PHPUnit\Framework\TestCase not found and could  
         not be autoloaded.". Include your files in "parameters >               
         autoload_paths".                                                       
         See https://github.com/rectorphp/rector#extra-autoloading".       
```

Even though I have this in my config :

```yaml
# rector.yaml
parameters:
    kernel_class: \SomeVendor\SomeBundle\Tests\App\AppKernel
    autoload_paths:
        - 'tests/App/config/bootstrap.php'
```

```php
<?php
# tests/App/config/bootstrap.php

declare(strict_types=1);

use SomeVendor\SomeBundle\Tests\App\AppKernel;
use Doctrine\Common\Annotations\AnnotationReader;
use Doctrine\Common\Annotations\AnnotationRegistry;

$file = __DIR__ . '/../../../vendor/autoload.php';
if (!file_exists($file)) {
    throw new RuntimeException('Install dependencies using Composer to run the test application.');
}
/** @noinspection PhpIncludeInspection */
$loader = require $file;

/* @see https://github.com/liip/LiipFunctionalTestBundle/blob/master/doc/caveats.md#use-a-bootstrap-file */
AnnotationRegistry::registerLoader([$loader, 'loadClass']);
AnnotationReader::addGlobalIgnoredName('group');
AnnotationReader::addGlobalIgnoredName('dataProvider');

return new AppKernel('test', $_ENV['TEST_KERNEL_DEBUG'] ?? true);
```

```json
# composer.json
    "autoload": {
        "psr-4": {
            "SomeVendor\\SomeBundle\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "SomeVendor\\SomeBundle\\Tests\\": "tests"
        }
    },
    "require-dev": {
        "symfony/phpunit-bridge": "^4.3"
    }
```

And 2) : 

```
 [ERROR] Could not process                                                      
         "src/someRandomCodeFile.php" file, due to:                                  
         "The binary                                                            
         "env_7cb87e4e880bbb75_BIN_PARALLEL_5dda0a93ed32c1487a4ed9d9a919fe4a"   
         for the command "parallel" cannot be found.".
```

This one is even stranger, because the "random code file" has *nothing* to do with "BIN_PARALLEL", which is used by some other part of our code and is defined as such : 

```yaml
# services.yaml
parameters:
    'env(BIN_PARALLEL)': /usr/bin/parallel
    bin.parallel: '%env(BIN_PARALLEL)%'

services:
    SomeService:
        arguments: ['%bin.parallel%']
```

It is `SomeService` that throws the exception if the path to the parallel bin does not exist.

Does that ring any bell to you ? Any idea what might be wrong from Rector's POV ?
Thanks for your help.
