### ISSUE TITLE
php70 refactor results in fatal error with equal named classes (but different namespace)

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#2226]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.5.20 (invoke `vendor/bin/rector --version`)          |
| PHP version    | PHP 7.2.9 (invoke `php -v`)                               |
| Full Command   | `rector process lib --set php70`  | 

## Minimal PHP Code Causing Issue

![image](https://user-images.githubusercontent.com/47448731/67935600-8089f080-fbca-11e9-8fbe-7c95d4781c3c.png)

leads to

```
Fatal error:  Cannot declare class portable\crossSelling\Warenkorb because the name is already in use in /home/runner/work/php-clxmobilenet-portable/php-clxmobilenet-portable/lib/portable/crossSelling/Warenkorb.php on line 12
```

## Expected Behaviour

No Fatal error

## my `rector.yml`
```
parameters:
  auto_import_names: true
  php_version_features: '7.0'
  autoload_paths:
    - 'bootstrap.php'
```
