### ISSUE TITLE
CompleteVarDocTypePropertyRector overrides comments

### ISSUE THREAD

**Issue by clxmstaab** [rectorphp/rector#2227]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.5.20    |
| PHP version    | PHP 7.2.9                        |
| Full Command   | `rector process models --set php70`  | 

## `rector.yml` 

```
parameters:
  auto_import_names: true
  php_version_features: '7.0'
  autoload_paths:
    - 'phpstan-bootstrap.php'
services:
  Rector\TypeDeclaration\Rector\Property\CompleteVarDocTypePropertyRector: ~
```

![image](https://user-images.githubusercontent.com/47448731/67955096-53513880-fbf2-11e9-885a-73e650369438.png)

## Expected

type should be changed but no comment overridden

## Actual

existing docs get overriden
