### ISSUE TITLE
"use" statement added twice and applied rectors not shown

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#2285]
<!-- First, thank you for reporting a bug. That takes time and we appreciate that! -->

| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.5.21
| PHP version    | PHP 7.2
| Full Command   | N/A  | 

This is the output of the `--dry-run`:

```diff
1 file with changes
===================

1) src/MyApp/Entity/User.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -18,6 +18,8 @@

 namespace App\MyApp\Entity;

+use function Safe\substr;
+use function Safe\substr;
 use ApiPlatform\Core\Annotation\ApiResource;
 use ApiPlatform\Core\Annotation\ApiSubresource;
 use Doctrine\Common\Collections\ArrayCollection;
@@ -188,10 +190,10 @@
             $tokenGenerator = new TokenGenerator();
         }

-        $plainPassword = \Safe\substr($tokenGenerator->generateToken(), 0, 12);
+        $plainPassword = substr($tokenGenerator->generateToken(), 0, 12);
         /** @var string $password The lenght is hardcoded (12 chars, with no special chars) */
         $password = $passwordEncoder->encodePassword($this, $plainPassword);
-        $password = \Safe\substr(str_replace(['/', '+', '='], ['', '', ''], $password), 0, 12);
+        $password = substr(str_replace(['/', '+', '='], ['', '', ''], $password), 0, 12);

         // Set the password for the user
         $this->setPlainPassword($password);
    ----------- end diff -----------

                                                                                                                        
 [OK] Rector is done! 1 changed files                                                                                   
                                                                                                                       
```

As you can see there are two problems with this file:

1. The applied rectors are not shown
2. The `use function Safe\substr` is added two times causing a fatal error.

**Comment by TomasVotruba** [comment]
This is not particular rule, but auto-import feature: 
https://github.com/rectorphp/rector#import-use-statements

Still, it should import it just once. This is a bug. I'll investigate

**Comment by TomasVotruba** [comment]
Btw, what is the full CLI command? I need it to reproduce

**Comment by Aerendir** [comment]
It is simply `vendor/bin/rector process src --dry-run`... Excuse me for the late reply: I0ve seen you was able to reproduce the bug anyway! Thank you!

**Comment by TomasVotruba** [comment]
Not sure it was the same bug though.

> It is simply vendor/bin/rector process src 

This command would fail, if there are 0 rules configured. What is the content of `rector.yaml` then?

Could you re-try with current `master`?

**Comment by Aerendir** [comment]
@TomasVotruba , but I have a lot of rules configured... This is the content:

```yaml
imports:
    #- { resource: 'vendor/rector/rector/config/level/architecture/*' }
    - { resource: 'vendor/rector/rector/config/set/php/php52.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php53.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php54.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php56.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php70.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php71.yaml'}
    #- { resource: 'vendor/rector/rector/config/level/php/php72.yaml'}
    - { resource: 'vendor/rector/rector/config/set/code-quality/*' }
    # Reactivate - { resource: 'vendor/rector/rector/config/level/coding-style/*' }
    - { resource: 'vendor/rector/rector/config/set/doctrine/doctrine25.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpstan/phpstan.yaml' }
    - { resource: 'vendor/rector/rector/config/set/sensio/*' }
    # Temporary disabled as throws errors
    #- { resource: 'vendor/rector/rector/config/level/symfony/symfony-code-quality.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony-constructor-injection.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony42.yaml' }
    # Disabled as it causes wrong changes in the code
    #- { resource: 'vendor/rector/rector/config/level/symfony/symfony-constructor-injection.yaml' }
    # Temporary disabled until https://github.com/thecodingmachine/safe/issues/116 is resolved
    - { resource: 'vendor/thecodingmachine/safe/rector-migrate.yml' }

parameters:
    php_version_features: '7.2'
    exclude_paths:
        - '*/Migrations/*'
    exclude_rectors:
        - 'Rector\CodeQuality\Rector\Identical\SimplifyBoolIdenticalTrueRector'
        - 'Rector\CodeQuality\Rector\Concat\JoinStringConcatRector'
        - 'Rector\CodingStyle\Rector\Identical\IdenticalFalseToBooleanNotRector'
        # This doesn't recognize the difference between classes and functions
        # Waiting the fix https://github.com/rectorphp/rector/issues/1376
        - 'Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector'
        - 'Rector\CodingStyle\Rector\Switch_\BinarySwitchToIfElseRector'
        # This wrongly transforms the return type hintings
        # See https://github.com/rectorphp/rector/issues/1435
        - 'Rector\Php\Rector\Name\ReservedObjectRector'
        # Has a bug: https://github.com/rectorphp/rector/issues/1431
        - 'Rector\Php\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector'
        # See https://github.com/rectorphp/rector/issues/1501
        - 'Rector\Php\Rector\BinaryOp\BinaryOpBetweenNumberAndStringRector'
        # See https://github.com/rectorphp/rector/issues/1504
        # See https://github.com/rectorphp/rector/issues/1503
        - 'Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector'
        # See https://github.com/rectorphp/rector/issues/1516
        - 'Rector\Php\Rector\FuncCall\RemoveExtraParametersRector'
        # See https://github.com/rectorphp/rector/issues/1522
        - 'Rector\Rector\Class_\RenameClassRector'
        # Seems has a bug: not yet reported
        - 'Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector'
        # Seems has a bug: not yet reported
        - 'Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector'

# This seems to be ignored and doesn't work
services:
    Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector:
        $shouldImportRootNamespaceClasses: false

```
