### ISSUE TITLE
[DX] Add paths to config

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#2301]
See https://github.com/phpstan/phpstan/commit/fc108af01b9df092fe0a31820729be315a71fbe1

## Before Only

```bash
vendor/bin/rector process src tests packages --set code-quality
```

## Now Also

```yaml
# rector.yaml
parameters:
    paths: 
        - 'src'
        - 'tests'
        - 'packages'
```

```bash
vendor/bin/rector process --set code-quality
```
