### ISSUE TITLE
Alert if a non existing Rector is excluded

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#2304]
In my `rector.yaml` file I have excluded a rector:

```yaml
parameters:
    ...
    exclude_rectors:
        ...
        - 'Rector\Rector\Class_\RenameClassRector'
        ...
```

It seems, anyway, that this rector was moved to `Rector\Renaming\Rector\Class_\RenameClassRector` but Rector doesn't alert me about the fact that I'm still excluding the old version.

I discovered that now the `RenameClass` rector is causing some bugs (https://github.com/rectorphp/rector/issues/2305) but, as I had it alread excluded, it required me some time until I discovered that I was excluding the wrong one as it was moved to a new position.

It will be really useful if Rector will alert about not still exsistent rectors to make easier to clean the `rector.yaml` file and avoid errors due to distraction like mine.
