### ISSUE TITLE
Unable to exclude specific file (specific filename), only path

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#2316]
Im trying to overcome #2307 by ignoring all files named `Exception.php` but this seems to not be possible. I am not sure if this is bug or feature request.

| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.5.21         |
| PHP version    | 7.3.4                               |
| Full Command   | `vendor/bin/rector p src/GpWebPay`  | 

## Current Behaviour 

I have corrupted file `src/GpWebPay/Exception.php` and i want to exclude it from rector processing, but still make it possible to process other files in this directory and i am not able to find working config for that.

## Minimal config

```yaml
parameters:
    exclude_paths:
        - 'Exception.php'
        - '*/Exception.php'
        - '**/Exception.php'
        - 'src/*/Exception.php'
        - 'src/**/Exception.php'
        - 'src/GpWebPay/Exception.php'
```

But file is still processed.

With this config file is ignored, but it is not desirable, because it ignores all files in the directory:
```yaml
parameters:
    exclude_paths:
        - 'src/GpWebPay/*'
```

## Expected Behaviour

To ignore and not process file `src/GpWebPay/Exception.php`
