### ISSUE TITLE
How to use Rector on a continuous integration 

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#2342]
I'm encountering some problems running Rector on a CI system.

I get a very long error that refers to PHPStan.

But the most strange thing is that the error refers to the `dev` environment while I've set it to be `test` (via an env var set directly in the server `APP_ENV`).

All other commands (PHPStan, Phan, bin/console ... commands, etc.) work as expected.

The only one that doesn't work is Rector. And I really don't understand which is the relation between Rector and PHPStan...

```console
vendor/bin/rector process src --dry-run
PHP Warning:  file_get_contents(/home/rof/src/github.com/My/App/vendor/phpstan/phpstan/../../../var/cache/dev/srcApp_KernelDevDebugContainer.xml): failed to open stream: No such file or directory in /home/rof/src/github.com/My/App/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 27
PHP Stack trace:
PHP   1. {main}() /home/rof/src/github.com/My/App/vendor/rector/rector/bin/rector:0
PHP   2. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->get() /home/rof/src/github.com/My/App/vendor/rector/rector/bin/rector:20
PHP   3. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->make() /home/rof/src/github.com/My/App/vendor/symfony/dependency-injection/Container.php:225
PHP   4. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /home/rof/src/github.com/My/App/vendor/symfony/dependency-injection/Container.php:249
PHP   5. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP   6. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getApplicationService.php:9
PHP   7. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP   8. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getProcessCommandService.php:9
PHP   9. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  10. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getRectorGuardService.php:9
PHP  11. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  12. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getRectorNodeTraverserService.php:9
PHP  13. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  14. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getVarToPublicPropertyRectorService.php:11
PHP  15. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  16. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getCommanderCollectorService.php:9
PHP  17. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  18. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getPropertyAddingCommanderService.php:9
PHP  19. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  20. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getClassManipulatorService.php:9
PHP  21. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  22. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getChildAndParentClassManipulatorService.php:9
PHP  23. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  24. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getParsedNodesByTypeService.php:11
PHP  25. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  26. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getNodeTypeResolverService.php:9
PHP  27. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  28. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getClassReflectionTypesResolverService.php:9
PHP  29. require() /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
PHP  30. Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct() /tmp/_rector/ContainerFr9PfxX/getBrokerService.php:9
PHP  31. PHPStan\DependencyInjection\ContainerFactory->create() /home/rof/src/github.com/My/App/vendor/rector/rector/packages/NodeTypeResolver/src/DependencyInjection/PHPStanServicesFactory.php:41
PHP  32. Container_ec8382eca6->getService() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php:80
PHP  33. Container_ec8382eca6->createService() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:118
PHP  34. Container_ec8382eca6->createServiceBroker() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:189
PHP  35. PHPStan\Broker\BrokerFactory->create() /tmp/cache/nette.configurator/Container_ec8382eca6.php:2868
PHP  36. PHPStan\DependencyInjection\Nette\NetteContainer->getServicesByTag() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/Broker/BrokerFactory.php:47
PHP  37. PHPStan\DependencyInjection\Nette\NetteContainer->tagsToServices() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:42
PHP  38. array_map() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:62
PHP  39. PHPStan\DependencyInjection\Nette\NetteContainer->PHPStan\DependencyInjection\Nette\{closure:/home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:60-62}() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:62
PHP  40. PHPStan\DependencyInjection\Nette\NetteContainer->getService() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:61
PHP  41. Container_ec8382eca6->getService() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:24
PHP  42. Container_ec8382eca6->createService() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:118
PHP  43. Container_ec8382eca6->createService0123() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:189
PHP  44. Container_ec8382eca6->getService() /tmp/cache/nette.configurator/Container_ec8382eca6.php:2526
PHP  45. Container_ec8382eca6->createService() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:118
PHP  46. Container_ec8382eca6->createService0122() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:189
PHP  47. PHPStan\Symfony\XmlServiceMapFactory->create() /tmp/cache/nette.configurator/Container_ec8382eca6.php:2517
PHP  48. file_get_contents() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php:27

Warning: file_get_contents(/home/rof/src/github.com/My/App/vendor/phpstan/phpstan/../../../var/cache/dev/srcApp_KernelDevDebugContainer.xml): failed to open stream: No such file or directory in /home/rof/src/github.com/My/App/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 27

Call Stack:
    0.0003     416376   1. {main}() /home/rof/src/github.com/My/App/vendor/rector/rector/bin/rector:0
    7.9851   26517184   2. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->get() /home/rof/src/github.com/My/App/vendor/rector/rector/bin/rector:20
    7.9851   26517184   3. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->make() /home/rof/src/github.com/My/App/vendor/symfony/dependency-injection/Container.php:225
    7.9851   26517560   4. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /home/rof/src/github.com/My/App/vendor/symfony/dependency-injection/Container.php:249
    7.9852   26523896   5. require('/tmp/_rector/ContainerFr9PfxX/getApplicationService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    7.9852   26524376   6. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getApplicationService.php:9
    7.9854   26535256   7. require('/tmp/_rector/ContainerFr9PfxX/getProcessCommandService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    7.9856   26536424   8. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getProcessCommandService.php:9
    7.9857   26538392   9. require('/tmp/_rector/ContainerFr9PfxX/getRectorGuardService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    7.9862   26538472  10. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getRectorGuardService.php:9
    7.9870   26605264  11. require('/tmp/_rector/ContainerFr9PfxX/getRectorNodeTraverserService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    7.9870   26605768  12. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getRectorNodeTraverserService.php:9
    7.9873   26624560  13. require('/tmp/_rector/ContainerFr9PfxX/getVarToPublicPropertyRectorService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0187   26830352  14. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getVarToPublicPropertyRectorService.php:11
    8.0188   26834272  15. require('/tmp/_rector/ContainerFr9PfxX/getCommanderCollectorService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0204   26840760  16. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getCommanderCollectorService.php:9
    8.0205   26842144  17. require('/tmp/_rector/ContainerFr9PfxX/getPropertyAddingCommanderService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0205   26842224  18. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getPropertyAddingCommanderService.php:9
    8.0206   26847928  19. require('/tmp/_rector/ContainerFr9PfxX/getClassManipulatorService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0206   26848120  20. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getClassManipulatorService.php:9
    8.0207   26850592  21. require('/tmp/_rector/ContainerFr9PfxX/getChildAndParentClassManipulatorService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0207   26850688  22. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getChildAndParentClassManipulatorService.php:9
    8.0208   26853016  23. require('/tmp/_rector/ContainerFr9PfxX/getParsedNodesByTypeService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0208   26853240  24. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getParsedNodesByTypeService.php:11
    8.0210   26864392  25. require('/tmp/_rector/ContainerFr9PfxX/getNodeTypeResolverService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0211   26866672  26. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getNodeTypeResolverService.php:9
    8.0212   26868016  27. require('/tmp/_rector/ContainerFr9PfxX/getClassReflectionTypesResolverService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0212   26868072  28. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->load() /tmp/_rector/ContainerFr9PfxX/getClassReflectionTypesResolverService.php:9
    8.0213   26869864  29. require('/tmp/_rector/ContainerFr9PfxX/getBrokerService.php') /tmp/_rector/ContainerFr9PfxX/HttpKernelRector_HttpKernel_RectorKernelProd7366226Container.php:367
    8.0213   26869920  30. Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct() /tmp/_rector/ContainerFr9PfxX/getBrokerService.php:9
    8.0363   27673928  31. PHPStan\DependencyInjection\ContainerFactory->create() /home/rof/src/github.com/My/App/vendor/rector/rector/packages/NodeTypeResolver/src/DependencyInjection/PHPStanServicesFactory.php:41
    8.0634   28966352  32. Container_ec8382eca6->getService() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php:80
    8.0634   28966352  33. Container_ec8382eca6->createService() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:118
    8.0634   28966776  34. Container_ec8382eca6->createServiceBroker() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:189
    8.0643   28989008  35. PHPStan\Broker\BrokerFactory->create() /tmp/cache/nette.configurator/Container_ec8382eca6.php:2868
    8.1196   31194640  36. PHPStan\DependencyInjection\Nette\NetteContainer->getServicesByTag() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/Broker/BrokerFactory.php:47
    8.1196   31194640  37. PHPStan\DependencyInjection\Nette\NetteContainer->tagsToServices() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:42
    8.1196   31196296  38. array_map() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:62
    8.1213   31231888  39. PHPStan\DependencyInjection\Nette\NetteContainer->PHPStan\DependencyInjection\Nette\{closure:/home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:60-62}() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:62
    8.1213   31231888  40. PHPStan\DependencyInjection\Nette\NetteContainer->getService() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:61
    8.1213   31231888  41. Container_ec8382eca6->getService() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php:24
    8.1213   31231888  42. Container_ec8382eca6->createService() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:118
    8.1214   31231936  43. Container_ec8382eca6->createService0123() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:189
    8.1261   31246120  44. Container_ec8382eca6->getService() /tmp/cache/nette.configurator/Container_ec8382eca6.php:2526
    8.1261   31246120  45. Container_ec8382eca6->createService() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:118
    8.1261   31246168  46. Container_ec8382eca6->createService0122() /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php:189
    8.1267   31259504  47. PHPStan\Symfony\XmlServiceMapFactory->create() /tmp/cache/nette.configurator/Container_ec8382eca6.php:2517
    8.1268   31259504  48. file_get_contents() /home/rof/src/github.com/My/App/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php:27

PHP Fatal error:  Uncaught PHPStan\Symfony\XmlContainerNotExistsException: Container /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/../../../var/cache/dev/srcApp_KernelDevDebugContainer.xml does not exist or cannot be parsed in /home/rof/src/github.com/My/App/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php:29
Stack trace:
#0 /tmp/cache/nette.configurator/Container_ec8382eca6.php(2517): PHPStan\Symfony\XmlServiceMapFactory->create()
#1 /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php(189): Container_ec8382eca6->createService0122()
#2 /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php(118): Nette\DI\Container->createService('0122')
#3 /tmp/cache/nette.configurator/Container_ec8382eca6.php(2526): Nette\DI\Container->getService('0122')
#4 /home/rof/src/github.com/My/App/vendor/nette/di/src/DI/Container.php(189): Container_ec8382eca6->createService0 in /home/rof/src/github.com/My/App/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 29

Fatal error: Uncaught PHPStan\Symfony\XmlContainerNotExistsException: Container /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/../../../var/cache/dev/srcApp_KernelDevDebugContainer.xml does not exist or cannot be parsed in /home/rof/src/github.com/My/App/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 29

PHPStan\Symfony\XmlContainerNotExistsException: Container /home/rof/src/github.com/My/App/vendor/phpstan/phpstan/../../../var/cache/dev/srcApp_KernelDevDebugContainer.xml does not exist or cannot be parsed in /home/rof/src/github.com/My/App/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 29

Call Stack:
    0.0003     416376   1. {main}() /home/rof/src/github.com/My/App/vendor/rector/rector/bin/rector:0
    7.9851   26517184   2. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->get() /home/rof/src/github.com/My/App/vendor/rector/rector/bin/rector:20
    7.9851   26517184   3. ContainerFr9PfxX\HttpKernelRector_HttpKernel_RectorKernelProd7366226Container->make() /home/rof/src/github.com/My/App/vendor/symfony/dependency-injection/Container.php:225
```

`rector.yaml`:
```yaml
imports:
    # See https://github.com/rectorphp/rector/issues/1543
    #- { resource: 'vendor/rector/rector/config/level/architecture/*' }
    - { resource: 'vendor/rector/rector/config/set/php/php52.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php53.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php54.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php56.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php70.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php71.yaml'}
    - { resource: 'vendor/rector/rector/config/set/php/php72.yaml'}
    - { resource: 'vendor/rector/rector/config/set/code-quality/*' }
    - { resource: 'vendor/rector/rector/config/set/coding-style/*' }
    - { resource: 'vendor/rector/rector/config/set/doctrine/doctrine25.yaml' }
    - { resource: 'vendor/rector/rector/config/set/phpstan/phpstan.yaml' }
    - { resource: 'vendor/rector/rector/config/set/sensio/*' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony-code-quality.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony-constructor-injection.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony42.yaml' }
    - { resource: 'vendor/rector/rector/config/set/symfony/symfony-constructor-injection.yaml' }
    # Temporary disabled until https://github.com/thecodingmachine/safe/issues/116 is resolved
    #- { resource: 'vendor/thecodingmachine/safe/rector-migrate.yml' }

parameters:
    php_version_features: '7.2'
    autoload_paths:
      - 'config/bootstrap.php'
    exclude_paths:
        - '*/Migrations/*'
    exclude_rectors:
        # I don't like those
        - 'Rector\CodeQuality\Rector\Identical\SimplifyBoolIdenticalTrueRector'
        - 'Rector\CodeQuality\Rector\Concat\JoinStringConcatRector'
        - 'Rector\CodingStyle\Rector\Identical\IdenticalFalseToBooleanNotRector'
        - 'Rector\SOLID\Rector\ClassMethod\UseInterfaceOverImplementationInConstructorRector'
        - 'Rector\CodingStyle\Rector\ClassMethod\NewlineBeforeNewAssignSetRector'
        - 'Rector\CodingStyle\Rector\Encapsed\EncapsedStringsToSprintfRector'
        - 'Rector\CodingStyle\Rector\Class_\AddArrayDefaultToArrayPropertyRector'
        # This doesn't recognize the difference between classes and functions
        # Waiting the fix https://github.com/rectorphp/rector/issues/1376
        - 'Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector'
        - 'Rector\CodingStyle\Rector\Switch_\BinarySwitchToIfElseRector'
        # See https://github.com/rectorphp/rector/issues/1431
        - 'Rector\Php\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector'
        # See https://github.com/rectorphp/rector/issues/1501
        - 'Rector\Php\Rector\BinaryOp\BinaryOpBetweenNumberAndStringRector'
        # See https://github.com/rectorphp/rector/issues/1504
        # See https://github.com/rectorphp/rector/issues/1503
        - 'Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector'
        # See https://github.com/rectorphp/rector/issues/1516
        - 'Rector\Php\Rector\FuncCall\RemoveExtraParametersRector'
        # See https://github.com/rectorphp/rector/issues/1522
        - 'Rector\Rector\Class_\RenameClassRector'
        # See https://github.com/rectorphp/rector/issues/1537
        - 'Rector\CodingStyle\Rector\Use_\RemoveUnusedAliasRector'
        # See https://github.com/rectorphp/rector/issues/1539
        - 'Rector\Php\Rector\String_\StringClassNameToClassConstantRector'
        # See https://github.com/rectorphp/rector/issues/1542
        - 'Rector\CodingStyle\Rector\Property\ArrayPropertyDefaultValueRector'
        # See https://github.com/rectorphp/rector/issues/2305
        - 'Rector\Renaming\Rector\Class_\RenameClassRector'
        # Causes a lot of troubles. See https://github.com/rectorphp/rector/issues?utf8=%E2%9C%93&q=is%3Aissue+ImportFullyQualifiedNamesRector
        - 'Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector'
        # Seems has a bug: not yet reported
        - 'Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector'
        # Seems has a bug: not yet reported
        - 'Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector'
        # Seems has a bug: not yet reported
        - 'Rector\SymfonyCodeQuality\Rector\Class_\EventListenerToEventSubscriberRector'
        # Seems has a bug: not yet reported
        # Wrongly removes extra parameters passed by FileManager:116 to CacheManager
        #          ---------- begin diff ----------
        #          --- Original
        #          +++ New
        #          @@ -116,7 +116,7 @@
        #        }
        #
        #          // Remove the thumbnail
        #            - $this->getCacheManager()->remove([$filePath], ['thumb_store_profile', 'thumb_purchase']);
        #          +        $this->getCacheManager()->remove([$filePath]);
        #
        #          return true;
        #        }
        #          ----------- end diff -----------
        - 'Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector'

# This seems to be ignored and doesn't work
services:
  Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector:
    $shouldImportRootNamespaceClasses: false
```
