### ISSUE TITLE
TypedPropertyRector does not remove docblocks

### ISSUE THREAD

**Issue by brendt** [rectorphp/rector#2367]
rector.yaml:

```yaml
parameters:
    php_version_features: '7.4'

services:
    Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector: ~
    Rector\Php74\Rector\Property\TypedPropertyRector: ~
```

```php
    /** @var string */
    public $name;
```

becomes

```php
    /** @var string */
    public string $name;
```

I expect it to be

```php
    public string $name;
```
