### ISSUE TITLE
rector database folder for laravel with laravel60 set fails

### ISSUE THREAD

**Issue by nwaweru** [rectorphp/rector#2398]
Hi,

I am trying to rector the database folder with the following command and it fails:

`vendor/bin/rector process database --set laravel60`

See error below on a new laravel project.

![rector-error](https://user-images.githubusercontent.com/4353067/70234971-eee64380-1772-11ea-8158-31cd99e9bc8a.png)

**Comment by TomasVotruba** [comment]
See the error, class needs to be autoloaded

**Comment by TomasVotruba** [comment]
Readme will help https://github.com/rectorphp/rector/blob/master/README.md#extra-autoloading

**Comment by francoism90** [comment]
@TomasVotruba I keep getting the same error:

```
// rector.yaml`

parameters:
  autoload_paths:
    - 'vendor/autoload.php'
  sets:
    - 'laravel60'
  exclude_paths:
    - '/*/bootstrap/*'
    - '/*/node_modules/*'
    - '/*/public/*'
    - '/*/storage/*'
    - '/*/vendor/*'
```

Thanks. :)
