### ISSUE TITLE
Use of undefined constant NON_MCA_MSG

### ISSUE THREAD

**Issue by alphamarket** [rectorphp/rector#2445]
Just upgraded the rector to the `v0.6.1` and when call the rector on a directory got the following warnings:

`PHP Warning:  Use of undefined constant NON_MCA_MSG - assumed 'NON_MCA_MSG' (this will throw an Error in a future version of PHP) in phar:///home/USER/.config/composer/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpParameterReflection.php on line 71`

**Comment by TomasVotruba** [comment]
- Is `NON_MCA_MSG` in your code? 
- What exact rector command do you run?
- What's inside your `rector.yaml`?

**Comment by alphamarket** [comment]
Yes I have `NON_MCA_MSG` constant in a class:

```PHP
<?php namespace App\Helpers;

use \App\Products;
class GoogleShopping  {
  /* ... */
  const NON_MCA_MSG = 'This operation cannot be run on multi-client accounts.';
  public function mustNotBeMCA($msg = NON_MCA_MSG) {
    if($this->config->isMCA) {
      throw new \InvalidArgumentException($msg);
    }
  }
  /* ... */
}
```
I use the `rector process app` command.

### rector.yml
```YML
parameters:
  php_version_features: '7.0'
  sets:
    - 'code-quality'
    - 'php71'
    - 'php72'
    - 'php73'
    - 'php74'
  autoload_paths:
    - app/Services/Registrar.php
    - app/Http/Middleware/noSecure.php
    - app/Helpers/Fpdf/makefont/ttfparser.php
    - app/Http/Controllers/CaseStudiesController.php
  exclude_paths:
    - app/Helpers/Fpdf/Fpdf.php
```
