### ISSUE TITLE
[Wordpress] Use Rector with Wordpress?

### ISSUE THREAD

**Issue by regenrek** [rectorphp/rector#2453]
## Question

Hi I'm playing around with rector and try to upgrade an old theme from 5.x to 7.2. So when I run 

```
vendor/bin/rector process --set php72 --dry-run
```

I have two errors which I'm not able to solve.

## Problem 1: Call to undefined function x()

The first is the `Call to undefined function x()` problem. Since wordpress exposes functions global like `[get_template_directory()](https://developer.wordpress.org/reference/functions/get_template_directory/)` or `add_filter()` and so on.

## Problem 2:

If you work on a theme you can access plugin classes if they exist.
Most of the plugins doesn't offer you an autoloader. So I run in this:

```
         "Analyze error: "Class myplugin\classes\field_input
         was not found while trying to analyse it - autoloading is probably
         not configured properly.". Include your files in "parameters >
         autoload_paths".
         See https://github.com/rectorphp/rector#extra-autoloading".
```

Is there any workaround or maybe can I ignore this errors somehow?

Thanks

**Comment by TomasVotruba** [comment]
1. These functions needs to be loaded, put file with them into `parameters > autoload_paths`

2. Better autoload it again the same way in 1, as you'll need that in the future, but you can skip it for now with `--hide-autoload-errors`

**Comment by regenrek** [comment]
Hey

thanks for the answer but lets say the `get_template_directory()` relies  in `theme.php` my `rector.yaml` will look like this?

```
services:
    Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector: ~

parameters:
    sets:
        - 'code-quality'
        - 'php71'
        - 'php72'
        - 'php73'
    exclude_paths:
        - 'web/app/plugins'
        - 'vendor/*'
    php_version_features: '7.3'
    paths:
        - 'web/app/themes'
    autoload_paths:
        - './vendor/autoload.php'
        - './web/app/themes/mjtheme-child/vendor/autoload.php'
        - './web/app/themes/mjtheme/vendor/autoload.php'
        - './web/wp/wp-includes/theme.php'
        - './web/wp/wp-includes/plugin.php'
        - './web/app/mu-plugins/mj-fewbricks/lib/fewbricks.php'
```

**Comment by TomasVotruba** [comment]
Looks good. What happens when you run it?

You can use `parameters > autoload_paths` or composer.json autoload

**Comment by TomasVotruba** [comment]
Closing as anwered with autoloading

**Comment by infabo** [comment]
I guess you can't run rector on WordPress. It has `require` everywhere. Relies on globals, defines and other stuff that I was not able to run rector. You can add several files  from `wp-includes` to autoload-path, but it comes the point, where it wants to access some globals and this is so awkward weird stuff from year 2003.

**Comment by TomasVotruba** [comment]
I see. It is technically possible to handle such cases, but it's not in Rector yet:
See https://github.com/rectorphp/rector/issues/4330

At current state, it's looking for contributor that will add this feature to Rector

**Comment by dingo-d** [comment]
I'm testing Rector a bit for PHP8, with the libs we are using at work for our WordPress themes and plugins, and this is my setup that seems to be working

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
	// get parameters
	$parameters = $containerConfigurator->parameters();

	// paths to refactor; solid alternative to CLI arguments
	$parameters->set(Option::PATHS, [__DIR__ . '/src', __DIR__ . '/tests']);

	$parameters->set(
		Option::AUTOLOAD_PATHS,
		[
			__DIR__ . '/vendor/squizlabs/php_codesniffer/autoload.php',
			__DIR__ . '/vendor/php-stubs/wordpress-stubs/wordpress-stubs.php',
		]
	);

	$parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_73);

	// auto import fully qualified class names? [default: false]
	$parameters->set(Option::AUTO_IMPORT_NAMES, true);

	// skip root namespace classes, like \DateTime or \Exception [default: true]
	$parameters->set(Option::IMPORT_SHORT_CLASSES, false);

	// Run Rector only on changed files
	$parameters->set(Option::ENABLE_CACHE, true);

	// Path to phpstan with extensions, that PHPSTan in Rector uses to determine types
	$parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, getcwd() . '/phpstan.neon.dist');

	// Define what rule sets will be applied
	$parameters->set(
		Option::SETS,
		[
			SetList::DEAD_CODE,
			SetList::PHP_80
		]
	);
};
```

Note that this is a [library](https://github.com/infinum/eightshift-libs/tree/release/3.1.0) that we use in our themes, so I guess it's a bit easier to run Rector on (it's not a super legacy code).

Note that I'm also using phpcs, phpstan and for all the WP functions I'm relying on [wordpress-stubs](https://github.com/php-stubs/wordpress-stubs) so that I don't have to load WP separately.

I think that all the requires and includes that usually plague themes should work after #5665 has been merged.

Btw super excited to try to play with Rector a bit more 😄

**Comment by TomasVotruba** [comment]
Thanks for the feedback :+1: 

> I think that all the requires and includes that usually plague themes should work after #5665 has been merged.

It currently in `dev-master`, we'll need a testing on real projects to resolve edge cases. Could you try it out? :)

**Comment by dingo-d** [comment]
I'll give it a go on my old themes, it was written in 'WordPress way' 😅  so I'll check how it works 🙂

**Comment by dingo-d** [comment]
Ok, I've tested [my old theme](https://themes.svn.wordpress.org/expire/1.1.4/) a bit with the following settings

`composer.json`

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/rectorphp/rector"
        }
    ],
    "require-dev": {
        "rector/rector": "dev-master",
        "szepeviktor/phpstan-wordpress": "^0.7.4",
        "phpstan/extension-installer": "^1.1",
        "wptrt/wpthemereview": "^0.2.1",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.1"
    }
}
```

`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
  level: max
  inferPrivatePropertyTypeFromConstructor: true
  checkMissingIterableValueType: false
  treatPhpDocTypesAsCertain: false
  paths:
    - /
  ignoreErrors:
    # Uses func_get_args()
    - '/^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$/'
```

`phpcs.xml.dist`
```xml
<?xml version="1.0"?>
<ruleset name="Expire">
  <description>Expire theme standards.</description>

  <rule ref="WPThemeReview"/>

  <exclude-pattern>*/vendor/*</exclude-pattern>

  <!-- Additional arguments. -->
  <arg value="sp"/>
  <arg name="basepath" value="."/>
  <arg name="parallel" value="8"/>
  <arg name="extensions" value="php"/>

  <file>.</file>

</ruleset>
```

And rector settings

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\DeadDocBlock\Rector\ClassMethod\RemoveUselessReturnTagRector;
use Rector\DeadDocBlock\Rector\Property\RemoveUselessVarTagRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    // paths to refactor; solid alternative to CLI arguments
    $parameters->set(Option::PATHS, [__DIR__ . '/src', __DIR__ . '/tests']);

    $parameters->set(
        Option::AUTOLOAD_PATHS,
        [
            __DIR__ . '/vendor/squizlabs/php_codesniffer/autoload.php',
            __DIR__ . '/vendor/php-stubs/wordpress-stubs/wordpress-stubs.php',
        ]
    );

    $parameters->set(Option::SKIP, [
        // or directory
        __DIR__ . '/vendor',
    ]);

    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_73);

    // auto import fully qualified class names? [default: false]
    $parameters->set(Option::AUTO_IMPORT_NAMES, true);

    // skip root namespace classes, like \DateTime or \Exception [default: true]
    $parameters->set(Option::IMPORT_SHORT_CLASSES, false);

    // Run Rector only on changed files
    $parameters->set(Option::ENABLE_CACHE, true);

    // Path to phpstan with extensions, that PHPSTan in Rector uses to determine types
    $parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, getcwd() . '/phpstan.neon.dist');

    // Define what rule sets will be applied
    $parameters->set(
        Option::SETS,
        [
            SetList::DEAD_CODE,
            SetList::PHP_74
        ]
    );

    // register single rule
    $services = $containerConfigurator->services();
    $services->set(RemoveUselessReturnTagRector::class);
    $services->set(RemoveUselessVarTagRector::class);
};
```

And when running `vendor/bin/rector process ./ --dry-run` I got

```bash
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Rector\NodeNameResolver\NodeNameResolver\FuncCallNameResolver::__construct(), 0 passed in /private/var/folders/mf/jxbsh3dd6zb43qy2mw1cgq1r0000gn/T/_rector/ContainerL3j6zgU/getNodeNameResolverService.php on line 51 and exactly 1 expected in /Users/denis.zoljom/Projects/Personal/expire/vendor/rector/rector/packages/node-name-resolver/src/NodeNameResolver/FuncCallNameResolver.php on line 23
```
