### ISSUE TITLE
Cannot redeclare dd()

### ISSUE THREAD

**Issue by voku** [rectorphp/rector#2616]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.9         |
| PHP version    | 7.2.25-1+ubuntu16.04.1+deb.sury.org+1                             |
| Full Command   | Framework/thirdparty/rector.phar process App/modules/Vertragsdatenbank --config App/scripts/githooks/rector.yaml --set coding-style --dry-run  | 

## Current Behaviour 
```
PHP Fatal error:  Cannot redeclare dd() (previously declared in phar:///home/lmoelleken/vdmg/Framework/thirdparty/rector.phar/vendor/autoload.php:371) in /home/lmoelleken/vdmg/Framework/includes/utility_functions.php on line 3082
```

## Expected Behaviour
no error because of a function like "dd()" :)

**Comment by TomasVotruba** [comment]
It looks like you're including autoloading twice.

What in `rector.yaml`?

**Comment by voku** [comment]
```
parameters:
    exclude_paths:
        - '*/composer/*'
        - '*/vendor/*'
        - '*/archiv/*'
        - '*/thirdparty/*'
        - '*/generated/*'
        - '*/_generated/*'
        - '*/tmp/*'
        - '*/shots/*'
        - '*/server/*'
    autoload_paths:
        - 'tests/_bootstrap.php'
```
