### ISSUE TITLE
drupal8-rector "...autoloading is probably not configured properly." error 

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#2754]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | v0.6.13--prefixed (invoke `vendor/bin/rector --version`)                   |
| PHP version    | PHP 7.3.9 (invoke `php -v`)                                        |
| Full Command   | vendor/bin/rector process web/modules/contrib/mailjet --dry-run            | 
| rector.yaml    | If you used own `rector.yaml` please provide its content              | 
```yml
imports:
  - { resource: "vendor/palantirnet/drupal8-rector/config/drupal-8/drupal-8-all-deprecations.yml" }
  # includes:
  # - { resource: "vendor/palantirnet/drupal8-rector/config/drupal-8/drupal-8.5-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal8-rector/config/drupal-8/drupal-8.6-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal8-rector/config/drupal-8/drupal-8.7-deprecations.yml" }

parameters:
  autoload_paths:
    - 'web/core'
    - 'web/core/modules'
    - 'web/modules'
    - 'web/profiles'

  file_extensions:
    - module
    - theme
    - install
    - profile
    - inc
    - engine

services: ~
```

## Current Behaviour 
We refactored and streamlined `palantirnet/drupal8-rector` to user rector-prefixed and include only 1 rule (DrupalSetMessageRector).

We created a development environment, that installs drupal8 and the latest `palantirnet/drupal8-rector`.

After running `vendor/bin/rector process web/modules/contrib/mailjet --dry-run --debug`, it applies successfully `DrupalSetMessageRector` rule to many files, but at the end it throws this error -
```
 [ERROR] Could not process                                                                                              
         "/Users/shaal/code/palantir/drupal8-rector-sandbox/web/modules/contrib/mailjet/lib/mailjet-api-php/src/mailjet.
         api.inc" file, due to:                                                                                         
         "Analyze error: "Class MailJet\MailJet was not found while trying to analyse it - autoloading is probably not  
         configured properly.". Include your files in "parameters > autoload_paths".                                    
         See https://github.com/rectorphp/rector#extra-autoloading".                                                    
```                                                       

## Steps to replicate the problem:

```
git clone git@github.com:palantirnet/drupal8-rector-sandbox.git
cd drupal8-rector-sandbox
composer require drupal/mailjet
vendor/bin/rector process web/modules/contrib/mailjet --dry-run --debug
```

## Expected Behaviour
(Run drupal8-rector smoothly with no errors)
