### ISSUE TITLE
How to make Rector pick the `test` version of the `App_KernelTestDebugContainer`?

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#2755]
On a Symfony app.

I've created a `rector.test.yaml` file containing this:

```yaml
imports:
    - { resource: 'rector.yaml' }

parameters:
    symfony_container_xml_path: 'var/cache/test/App_KernelTestDebugContainer.xml'
```

Then I have my `rector.yaml` file that I use locally.

The problem is that running this command

```console
./vendor/bin/rector process src --dry-run --debug -v --config ./rector.test.yaml
```

I continue to get this error

> PHP Warning:  file_get_contents(/home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan/../../../var/cache/dev/App_KernelDevDebugContainer.xml): failed to open stream: No such file or directory in /home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 27

This is the full GitHub Action:

```yaml
name: Rector

on: [push, pull_request]

jobs:
    serendipity_hq:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        name: Test
        env:
            APP_ENV: test
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: '7.2'
                  coverage: none # disable xdebug, pcov
                  tools: prestissimo
                  extensions: intl

            - name: Install Composer deps
              run: |
                  composer update --no-interaction --no-suggest
                  php bin/console cache:clear --env=test
                  php bin/console assets:install

            - name: Run Rector
              run: |
                  ./vendor/bin/rector process src --dry-run --debug -v --config ./rector.test.yaml
```

As you can see, I re-generate the cache running `php bin/console cache:clear --env=test`, but then Rector is not able to pick the right `App_KernelTestDebugContainer` but continues to pick `App_KernelDevDebugContainer`.

Any ideas about how to fix this?

This is the full log
```console
Run ./vendor/bin/rector process src --dry-run --debug -v --config ./rector.test.yaml
  ./vendor/bin/rector process src --dry-run --debug -v --config ./rector.test.yaml
  shell: /bin/bash -e {0}
  env:
    APP_ENV: test
File "/home/runner/work/app-my-app-www/app-my-app-www/vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 65"
File "/home/runner/work/app-my-app-www/app-my-app-www/vendor/rector/rector/../../autoload.php" is about to be loaded in "AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 97"
PHP Warning:  file_get_contents(/home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan/../../../var/cache/dev/App_KernelDevDebugContainer.xml): failed to open stream: No such file or directory in /home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 27
Warning: file_get_contents(/home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan/../../../var/cache/dev/App_KernelDevDebugContainer.xml): failed to open stream: No such file or directory in /home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 27
PHP Fatal error:  Uncaught PHPStan\Symfony\XmlContainerNotExistsException: Container /home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan/../../../var/cache/dev/App_KernelDevDebugContainer.xml does not exist in /home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php:29
Stack trace:
#0 /tmp/cache/nette.configurator/Container_e3cbda68ff.php(3306): PHPStan\Symfony\XmlServiceMapFactory->create()
#1 phar:///home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Container.php(146): Container_e3cbda68ff->createService0150()
#2 phar:///home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Container.php(88): _HumbugBox951e2b87c765\Nette\DI\Container->createService('0150')
#3 /tmp/cache/nette.configurator/Container_e3cbda68ff.php(3315): _HumbugBox951e2b87c765\Nette\DI\Container->getService('0150')
#4 phar:///home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan in /home/runner/work/app-my-app-www/app-my-app-www/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 29
```
