### ISSUE TITLE
Pluralization in Symfony 4.2+

### ISSUE THREAD

**Issue by enumag** [rectorphp/rector#2782]
In Symfony 4.1 and older, pluralization was handled by `TranslatorInterface::transChoice()` with a format like this:

```yaml
some:
  number_of_items: "{0} No items found.|{1} One item found.|]1,Inf[ %count% items found."
```

In Symfony 4.2 `transChoice` as well as this format are deprecated in favor of the [IntlMessageFormatter](https://symfony.com/blog/new-in-symfony-4-2-intlmessageformatter) which uses this format:

```yaml
some:
  number_of_items: "{count, plural,
        =0 {No items found.}
        one {One item found.}
        other {# items found.}
      }"
# Or without newlines and/or nested inside some sentence:	  
some:
  number_of_items: "{count, plural, =0 {No items found.} one {One item found.} other {# items found.}}"
```

Do you know of any tool that would help me migrate my yamls accordingly?
