### ISSUE TITLE
[Rector] Add class constant visibility

### ISSUE THREAD

**Issue by Lexinek** [rectorphp/rector#285]
<img width="555" alt="screenshot 2018-01-13 22 41 35" src="https://user-images.githubusercontent.com/3995003/34910336-f81a490a-f8b2-11e7-8c6c-c638a95c8aaa.png">

@TomasVotruba  I know this can be easily fixed using find&replace - that is why i am opening issue, would you be interested in (me) writing this rector and sending PR?

## Usecase:
before:
```php
const PAID_BY_CASH = 'paidByCash';
```

after:
```php
public const PAID_BY_CASH = 'paidByCash';
```

**Comment by TomasVotruba** [comment]
Hey @Lexinek 

This is already handled by [EasyCodingStandard](https://github.com/symplify/easyCodingStandard/) with `PhpCsFixer\Fixer\ClassNotation\VisibilityRequiredFixer`:

```yaml
checkers:
    # All elements should have visibility
    PhpCsFixer\Fixer\ClassNotation\VisibilityRequiredFixer:
        elements: [const, property, method]
```

or better 

```yml
includes:
    - vendor/symplify/easy-coding-standard/config/php71.neon
```
