### ISSUE TITLE
rector-prefixed 0.7 throw PhpStormStubsMap errors

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#2878]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | v0.7 (invoke `vendor/bin/rector --version`)                   |
| PHP version    | PHP 7.3 (invoke `php -v`)                                        |
| Full Command   | vendor/bin/rector process web/modules/contrib/config_filter --set dead-code --dry-run           | 
| Demo link      |  | 
| rector.yaml    | (see below) | 
```
imports:
  - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8-all-deprecations.yml" }
  # includes:
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.5-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.6-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.7-deprecations.yml" }

parameters:
  autoload_paths:
    - 'web/core'
    - 'web/core/modules'
    - 'web/modules'
    - 'web/profiles'

  file_extensions:
    - module
    - theme
    - install
    - profile
    - inc
    - engine

services: ~
```
## Current Behaviour 

Rector 0.6.13 is working as expected.
Steps to replicate:
- `git clone git@github.com:palantirnet/drupal8-rector-sandbox.git`
- `cd drupal8-rector-sandbox/`
- `git checkout rector-0.7`
- `composer install`
- `vendor/bin/rector process web/modules/contrib/config_filter --set dead-code --dry-run`

## Minimal PHP Code Causing Issue

  

```php
<?php 

// put file content here
```
