### ISSUE TITLE
Rector 0.7.2 is testing for additional rules that were NOT set in rector.yml

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#2958]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.2              |
| Installed as   | prefixed Rector PHAR                      |

rector.yml content:
```
imports:
  - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8-all-deprecations.yml" }
  # includes:
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.5-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.6-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.7-deprecations.yml" }

parameters:
  autoload_paths:
    - 'web/core'
    - 'web/core/modules'
    - 'web/modules'
    - 'web/profiles'

  file_extensions:
    - module
    - theme
    - install
    - profile
    - inc
    - engine

services: ~
```

## Minimal PHP Code Causing Issue

I tried creating something, I am not sure if it represent the actual issue -
testing with set "twig240", but it seems to fix double spaces.
https://getrector.org/demo/eafad324-ce23-4db8-83f9-b6b28a06e048#result

I created 2 github tests. Both installing Drupal + Rector.
1. running rector 0.6.13
2. running rector 0.7.2

When running rector 0.6.13, rector finds nothing to fix on a specific php file -
https://github.com/rectorphp/rector/pull/2957/checks?check_run_id=475699095#step:4:209

When running rector 0.7.2, rector finds A LOT of fixes on the same php file, with same rector.yml file -
https://github.com/rectorphp/rector/pull/2957/checks?check_run_id=475698851#step:4:388

## Expected Behaviour

I expect Rector to apply only the rules that are requested through the config file and nothing else.
