### ISSUE TITLE
Class 'Symplify\PackageBuilder\Yaml\ParameterInImportResolver' not found

### ISSUE THREAD

**Issue by tomasnorre** [rectorphp/rector#2973]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.6.13 & v0.6.14             |
| Installed as   | composer dependency                     |

When running `vendor/bin/rector process --dry-run --config rector-ci.yaml` 

I get following error:
```
[ERROR] Class 'Symplify\PackageBuilder\Yaml\ParameterInImportResolver' not found
```

I haven't update any dependencies, and all the sudden my travis-ci started to fail.
https://travis-ci.org/AOEpeople/crawler/jobs/656774321#L503

I've tried, as a fix, to update my rector to v0.7.x, but my code not yet quite ready for it.

## Expected Behaviour

I would expect not having a class not found issue. Earlier today until i tried updating the rector locally the command was working locally as well. 

But after upgrading and downgrading to v0.6.14 again, i get the error locally as well. 

`rector-ci.yaml`
```
parameters:
    paths:
        - "Classes"
        - "Configuration"
        - "Tests"

    sets:
        - "dead-code"

    auto_import_names: false

    autoload_paths:
        - "Classes"

    exclude_paths:
        # missing parent interface "TYPO3\CMS\IndexedSearch\Worker\WorkerInterface"
        - "Classes/Worker/CrawlerWorker.php"
```
