### ISSUE TITLE
Running coding-style set on a folder produces errors

### ISSUE THREAD

**Issue by damontgomery** [rectorphp/rector#3183]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.6.13              |
| Installed as   | prefixed Rector PHAR                      |

When I add the `coding-style` set and run it on a folder (rector_examples), I get the following error.

```
 [ERROR] Could not process "/Users/dan/Sites/drupal-rector-sandbox/drupal-rector/rector_examples/src/DBSelectStatic.php"
         file, due to:
         "Analyze error: "Class Drupal\core\Database\Database was not found while trying to analyse it - autoloading is
         probably not configured properly.". Include your files in "parameters > autoload_paths".
         See https://github.com/rectorphp/rector#extra-autoloading".
```

These errors are not produced when I run the set against the individual file reporting the issue.

Our code is available at https://github.com/palantirnet/drupal-rector/pull/42.

## Minimal PHP Code Causing Issue

In our code, https://github.com/palantirnet/drupal-rector/pull/42

And the following configuration file

```
parameters:
  autoload_paths:
    - 'web/core'
    - 'web/core/modules'
    - 'web/modules'
    - 'web/profiles'

  file_extensions:
    - module
    - theme
    - install
    - profile
    - inc
    - engine

  sets:
    - 'coding-style'

services: ~
```
You see these issues.

## Expected Behavior

As indicated in the error, the updates are not applied.
