### ISSUE TITLE
Running ImportFullyQualifiedNamesRector on a folder produces incorrect results

### ISSUE THREAD

**Issue by damontgomery** [rectorphp/rector#3184]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.6.13              |
| Installed as   | prefixed Rector PHAR                      |

Using the code in https://github.com/palantirnet/drupal-rector/pull/42

When I run the command against the `rector_examples` folder, incorrect `use` statements are added or short classes are substituted and no `use` statements are added.

When I run this against individual files, it works as expected.

This works correctly for classes and does not work for static files for us.

For example, `use Drupal\core\Database\Database;` is added to `url_updated.php`, but `Database` is not used at all in that file.

In other examples, no `use` statement is added to `unicode_strtolower.php`, but the short class name is substituted.

## Minimal PHP Code Causing Issue

The code in https://github.com/palantirnet/drupal-rector/pull/42

With configuration file

```
parameters:
  autoload_paths:
    - 'web/core'
    - 'web/core/modules'
    - 'web/modules'
    - 'web/profiles'

  file_extensions:
    - module
    - theme
    - install
    - profile
    - inc
    - engine

services:
  # This Rector will add 'use' statements.
  Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector: ~
```

## Expected Behaviour

Use statements are only added for classes in the file.
Use statements are added when short class names are substituted.
