### ISSUE TITLE
Additional rectors are ran despite not being referenced in my config

### ISSUE THREAD

**Issue by nesk** [rectorphp/rector#3212]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.16              |
| Installed as   | composer dependency                      |

First, thank you so much for this awesome project! I'm currently encountering some issues and hope you could provide some help.

I've created the following config:

```yaml
parameters:
    autoload_paths:
        - bin/.phpunit/phpunit-7.5/vendor/autoload.php
    symfony_container_xml_path: var/cache/dev/App_KernelDevDebugContainer.xml

services:
    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            App\Security\PermissionResolver: App\Security\Permission\PermissionResolver

```

If I run `vendor/bin/rector show`, I get something that seems to be the appropriate result:

```
Rector v0.7.16
Config file: rector.yaml

 * Rector\PostRector\Rector\UseAddingPostRector
 * Rector\Renaming\Rector\Class_\RenameClassRector
      oldToNewClasses:
          App\Security\PermissionResolver: App\Security\Permission\PermissionResolver

 * Rector\PostRector\Rector\PropertyAddingPostRector
 * Rector\PostRector\Rector\NodeToReplacePostRector
 * Rector\PostRector\Rector\NodeRemovingRector
 * Rector\PostRector\Rector\NodeAddingPostRector
 * Rector\PostRector\Rector\NameImportingPostRector
      importDocBlocks: true
```

However, when I run `vendor/bin/rector process src --dry-run`, the outputted diffs contain **way more** modifications than expected (~12 files):

```
62 files with changes
```

Mainly, the additional diffs are avbout code quality (which is good, but I don't want them now), for example:

```diff
     /**
      * @var boolean
      *
-     * @ORM\Column(name="devOnly", type="boolean", nullable=false, options={"default"="0"})
+     * @ORM\Column(name="devOnly", type="boolean", nullable=false, options={"default":"0"})
      * @JMS\Groups({"default"})
-     *
      */
     private $devOnly = false;
```

And sometimes there's some pretty weird changes:

- why removing the route methods?

```diff
 class DefaultController extends AbstractController
 {
     /**
-     * @Route(
-     *     path="/some-endpoint",
-     *     methods = { "POST" }
-     * )
+     * @Route(     path="/some-endpoint" )
      */
     public function someAction(Request $request)
     {
```

- why removing `joinColumns` and `inverseJoinColumns`?
```diff
      * @var ArrayCollection $clusters
      * @JMS\Groups({"details"})
      * @ORM\ManyToMany(targetEntity="Cluster", inversedBy="campaigns")
-     * @ORM\JoinTable(name="PushCampaignCluster",
-     *      joinColumns = {
-     *          @ORM\JoinColumn(name="pushCampaignId", referencedColumnName="id")
-     *      },
-     *      inverseJoinColumns = {
-     *          @ORM\JoinColumn(name="clusterId", referencedColumnName="id")
-     *      }
-     * )
-     *
+     * @ORM\JoinTable(name="PushCampaignCluster"
+     *      )
      */
     private $clusters;
```

Unfortunately, I'm unable to create a reproducible example, I'm really for this and I know it will not help. 😕

I was hoping maybe you have any idea how this could happen so I can investigate further more? If needed, I can provide more diff examples.

Thank you
