### ISSUE TITLE
Rector doesn't work without `sets`

### ISSUE THREAD

**Issue by SergeC** [rectorphp/rector#3274]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.x-dev@40275b2              |
| Installed as   | composer dependency "rector/rector-prefixed": "^0.7.21"                      |

I want to run Rector with a few services only on my project. I don't need bundled sets.

## Minimal PHP Code Causing Issue

My config file looks like as follows
```YAML
parameters:
  auto_import_names: true
  import_short_classes: false
  import_doc_blocks: false
  php_version_features: '7.4'
  paths:
    - 'src'
  services:
    Rector\Core\Rector\Property\PropertyToMethodRector:
      $perClassPropertyToMethods:
        ....Module:
          id:
            get: getId
            set: setId
```

## Expected Behaviour

Rector should use listed services but gives an error instead:

```
vendor/bin/rector process --dry-run --config rector.yaml
Rector 0.8.x-dev@40275b2
Config file: rector.yaml


In RectorGuard.php line 34:
                                                    
  We need some rectors to run:                      
  * register them in rector.yaml under "services:"  
  * use "--set <set>"                               
  * or use "--config <file>.yaml"                   
                                                 
```

An error message states that I must have `services` and I have them. It doesn't work without `sets`.
