### ISSUE TITLE
Creating your own set

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#3430]
# Question
So in the documentation you show us how to create your own rule, however I want to put my code in multiple rules like most of the more advanced stuff does here in rector by using sets.

How do we create our own set?

**Comment by TomasVotruba** [comment]
Set is bunch of rules in one config. You can use it like Symfony config (it is a Symfony config):

```yaml
# my-custom-set.yaml
services:
	FirstRector: null
	SecondRector: null
```

```yaml
vendor/bin/rector process src --config my-custom-set.yaml
```

<br>

Note: `--set` is basially shortcut for internal Rector configs. So instead of `--config vendor/rector/rector/config/set/php71.yaml` you can use only `--set php71`.
