### ISSUE TITLE
Change ArgumentReplacerRector to ArgumentRector

### ISSUE THREAD

**Issue by EdoBarnas** [rectorphp/rector#356]
Using this rector:
```
Rector\Rector\Dynamic\ArgumentRector:
    $argumentByMethod:
        -
            type: 'add'
            class: 'Sylius\Component\Core\Model\OrderInterface'
            method: 'getLastPayment'
            position: 0 # as append | default value is 0, config argument need not be listed
            typehint: false # default value is false, config argument need not be listed
            property: '$state'
            default_value: PaymentInterface::STATE_NEW
            can_be_nullable: # default value is false, config argument need not be listed
```

Possible types:
- **add** for adding new argument
- **replace** for replacing existing argument
- **remove** for removing existing argument
