### ISSUE TITLE
Difference between RenameMethodCallRector and RenameMethodRector

### ISSUE THREAD

**Issue by alfredbez** [rectorphp/rector#3598]
# Question
What is the difference between [RenameMethodCallRector](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#renamemethodcallrector) and [RenameMethodRector](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#renamemethodrector)?

Here's the example from the documentation:

```yaml
services:
    Rector\Renaming\Rector\MethodCall\RenameMethodCallRector:
        SomeExampleClass:
            oldMethod: newMethod
```
```yaml
services:
    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        SomeExampleClass:
            $oldToNewMethodsByClass:
                oldMethod: newMethod
```

The diff is the same for both examples:
```diff
 $someObject = new SomeExampleClass;
-$someObject->oldMethod();
+$someObject->newMethod();
```
