### ISSUE TITLE
Impossibile to use Rector in test environment (due to PHPStan use)

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#3642]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.41              |

# Error reported
> PHP Warning:  file_get_contents(/path/to/app/vendor/phpstan/phpstan/../../../var/cache/dev/srcApp_KernelDevDebugContainer.xml): failed to open stream: No such file or directory in /path/to/app/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 27

# Description of the issue

Trying to run Rector in CI we get the above error, caused by PHPStan that cannot find the container compiled in `dev`: in fact we are in `test` env, and so the `dev` container doesn't exist.

# Steps to reproduce the issue

In a Symfony app:

1. Manually remove the folder `var/cache/dev`
2. Recreate the cache for the `test` env running `bin/console cache:clear --env test`
3. Create the file `rector.yaml` (see below for the contents of the file)
4. Create the file `rector.test.yaml` (see below for the content of the file)
5. Run Rector loading the `test` config file: `vendor/bin/rector process src --dry-run --config=rector.test.yaml`

## `rector.yaml`

```
parameters:
    php_version_features: '7.2'
    sets:
      - 'php52'
      - 'php53'
      - 'php54'
      - 'php56'
      - 'php70'
      - 'php71'
      - 'php72'
      - 'code-quality'
      - 'coding-style'
      - 'doctrine'
      - 'phpstan'
      - 'framework-extra-bundle-30'
      - 'framework-extra-bundle-40'
      - 'framework-extra-bundle-50'
      - 'symfony-code-quality'
      - 'symfony-constructor-injection'
      - 'symfony42'
    autoload_paths:
      - 'config/bootstrap.php'
    exclude_paths:
        - '*/Migrations/*'
```

## `rector.test.yaml`

```
imports:
  - { resource: 'rector.yaml'}

parameters:
  symfony_container_xml_path: 'var/cache/test/srcApp_KernelTestDebugContainer.xml'
```
