### ISSUE TITLE
Formatting bug for Symfony Constraints

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#3645]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@0a8bef3             |
| Installed as   | docker latest image                      |

```diff
 <?php

 use Symfony\Component\Validator\Constraints as Assert;

 class User
 {
     /**
-     * @Assert\Email(message = "email.email")
+     * @Assert\Email(message=email.email)
      */
     private $email;
 }
```

## Expected Behaviour

Rector should not touch it.

SF 4.4 application. My rector.yaml:
```yaml
services:
    Rector\Php74\Rector\Property\TypedPropertyRector:
    Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector:

parameters:
    auto_import_names: true
    import_short_classes: false
    autoload_paths:
        - /project/config/bootstrap.php 
```
Can't run demo, getting ` Function 'mail()' is not allowed.`.
![Screenshot at 2020-07-03 18-09-59](https://user-images.githubusercontent.com/25783196/86485218-78391500-bd58-11ea-8702-9587b34b7623.png)
