### ISSUE TITLE
Could not process ClassName.php,  file, due to: "Argument 1 passed to PhpParser\PrettyPrinterAbstract::pModifiers() must be of the type integer, null given"

### ISSUE THREAD

**Issue by localhorst** [rectorphp/rector#3659]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.27             |
| Installed as   | composer dependency  (minimum stability: stable)          |

I am getting errors  when executing
"./vendor/bin/rector process htdocs/typo3conf/ext/ppw_sitepackage --config=rectorconfig.yaml --dry-run"

Rector suggests some modifications, but ends in several errors. 
Without the dry-run option, file is modified, but errors persist.

## Errors

```
Rector v0.7.27
Config file: rectorconfig.yaml


 [ERROR] Could not process "htdocs/typo3conf/ext/my_sitepackage/Classes/Controller/LoginController.php" file, due to:
         "Argument 8 passed to PHPStan\Analyser\MutatingScope::__construct() must implement interface
         PHPStan\Parser\Parser, instance of PHPStan\Analyser\ScopeContext given, called in
         /srv/apache2/martin/bornheim/vendor/rector/rector/packages/node-type-resolver/src/PHPStan/Scope/ScopeFactory.ph
         p on line 77".


 [ERROR] Could not process "htdocs/typo3conf/ext/my_sitepackage/Classes/Controller/LoginController.php" file, due to:
         "Look at "Rector\NodeTypeResolver\NodeTypeResolver\ClassAndInterfaceTypeResolver::resolve()" on line 53".

```

Code example:
htdocs/typo3conf/ext/my_sitepackage/Classes/Controller/LoginController.php

```
<?php
namespace MyVendor\MySitepackage\Controller;

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Fluid\View\StandaloneView;

class LoginController extends \TYPO3\CMS\Backend\Controller\LoginController
{
    protected function getFluidTemplateObject()
    {
        /** @var StandaloneView $view */
        $view = GeneralUtility::makeInstance(StandaloneView::class);
        $view->setLayoutRootPaths([GeneralUtility::getFileAbsFileName('EXT:backend/Resources/Private/Layouts')]);
        $partialPaths = [
            GeneralUtility::getFileAbsFileName('EXT:backend/Resources/Private/Partials'),
            GeneralUtility::getFileAbsFileName('EXT:ppw_sitepackage/SubPackages/backend/Resources/Private/Partials')
        ];
        $view->setPartialRootPaths($partialPaths);
        $view->setTemplateRootPaths([GeneralUtility::getFileAbsFileName('EXT:backend/Resources/Private/Templates')]);

        $view->getRequest()->setControllerExtensionName('Backend');
        return $view;
    }
}
```

rectorconfig.yaml
```

# taken from ssch/typo3-rector
parameters:
    # FQN classes are not imported by default. If you don't to do do it manually after every Rector run, enable it by:
    auto_import_names: true
    # this will not import root namespace classes, like \DateTime or \Exception
    import_short_classes: false
    # this will not import classes used in PHP DocBlocks, like in /** @var \Some\Class */
    import_doc_blocks: true
    php_version_features: '7.2'
imports:
    - { resource: 'vendor/ssch/typo3-rector/config/typo3-95.yaml' }
```

typo3-95.yaml:
https://github.com/sabbelasichon/typo3-rector/blob/master/config/typo3-95.yaml

Reproducing the issue using https://getrector.org/demo/ was not possible. 

## Expected Behaviour

Rector modifying files (or suggesting modifications) without errors.

Maybe the rectors at @sabbelasichon 's ssch/typo3-rector are at fault, but more probably this is related to my misssing understanding of the rector library and which settings / versions to use. 

If someone could direct me to an approach how to debug this, I'd be happy.
