### ISSUE TITLE
\ being added to built in functions in 0.7.54, works correctly in 0.7.53

### ISSUE THREAD

**Issue by phpfui** [rectorphp/rector#3814]
# Bug Report

| Subject           | Details           |
| -------------- | --------------|
| Rector version | 0.7.54           |

Standard built in functions in PHP are being prepended with the root namespace causing PHPStan to barf.  For example, count becomes \count.  While I don't think that is technically illegal PHP, it is not needed and causes unexpected T_NS_SEPARATOR errors in PHPStan.  Works in 0.7.53.

## Minimal PHP Code Causing Issue

```php
class Comet
{
    function name()
    {
       ob_start();
    }
}
```

## Rector.yaml (can't seem to convert it to PHP yet)

```YAML
parameters:
    php_version_features: '5.6'
services:
    Rector\Legacy\Rector\Include_\RemoveIncludeRector: null
```

## Expected Behaviour

Nothing should change in file.  Rector returns \ob_start();  Code needs to be in method in class.  Stand alone function call, or function call in function work correctly.
