### ISSUE TITLE
Is there a way to restrict which return types Rector annotates?

### ISSUE THREAD

**Issue by MrMage** [rectorphp/rector#3900]
I am trying to "refine" my Laravel 6/PHP 7.4 project with Rector. While I appreciate Rector's automatic annotation with return types, there are cases where I would like to avoid this behavior. For example,

```
public function edit(Request $request, TeamMembership $teamMembership)
```

gets replaced with

```
public function edit(Request $request, TeamMembership $teamMembership): \Illuminate\View\View
```

Unfortunately, the new line will break if I ever e.g. return a redirect from that controller method.

Therefore, **is there a way to prevent Rector from adding return type annotations if the return type matches a specific pattern**?

**rector.yaml:**
```yaml
parameters:
    php_version_features: '7.4'
    auto_import_names: false
    import_short_classes: false
    sets:
        - code-quality
        #- coding-style
        #- laravel60
        #- laravel-static-to-injection
        #- array-str-functions-to-static-call
        #- php72
        #- php73
        #- php74
        #- phpstan
        #- type-declaration
        #- dead-code
    paths:
        - 'app/Http'
        #- 'tests'
    exclude_paths:
        - 'bootstrap/cache/*'
        - 'storage/*'
        - 'vendor/*'
        - 'storage/*'
        - '*/Protos/*'
        - '*.blade.php'

services:
    Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector: ~
    Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector: ~
    Rector\TypeDeclaration\Rector\Property\CompleteVarDocTypePropertyRector: ~
```
