### ISSUE TITLE
Let Rector\Rector\Dynamic\ArgumentRector add argument

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#398]
Based on #353 

```yaml
    # @todo, use this and add new argument to a method
    Rector\Rector\Dynamic\ArgumentRector:
        $argumentByMethod:
             # Add state argument to the getLastPayment($state), where $state is target last payment state. getLastPayment(PaymentInterface::STATE_NEW)
            -
                type: 'add'
                class: 'Sylius\Component\Core\Model\OrderInterface'
                method: 'getLastPayment'
                position: 0 # as append | default value is 0, config argument need not be listed
                typehint: false # default value is false, config argument need not be listed
                property: '$state'
                default_value: PaymentInterface::STATE_NEW
```
