### ISSUE TITLE
Add Rector\Rector\Dynamic\ReturnTypehintRector

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#399]
Mentioned in #353 

```yaml
     @todo, use this and change typehint of return value
    Rector\Rector\Dynamic\ReturnTypehintRector:
            $returnTypehintByMethod:
                # OrderInterface::getAdjustmentsRecursively and OrderItemInterface::getAdjustmentsRecursively return types changed from array to Collection
                'Sylius\Component\Order\Model\OrderInterface':
                    'getAdjustmentsRecursively':
                        'array': 'Doctrine\Common\Collections\Collection'

                'Sylius\Component\Order\Model\OrderItemInterface':
                    'getAdjustmentsRecursively':
                        'array': 'Doctrine\Common\Collections\Collection'

                # PrioritizedServiceRegistryInterface::all method return type changed from Zend's PriorityQueue to iterable
                'Sylius\Component\Registry\PrioritizedServiceRegistryInterface':
                    'all':
                        'Zend\Stdlib\PriorityQueue': 'iterable'
```
