### ISSUE TITLE
Chained methods are not fixed using MethodNameReplacerRector

### ISSUE THREAD

**Issue by tigitz** [rectorphp/rector#496]
While trying to implement Symfony 4.1 upgrades through rector I used

```yml
services:
    Rector\Rector\Dynamic\MethodNameReplacerRector:
        $perClassOldToNewMethods:
            # Console
            'Symfony\Component\Console\Helper\TableStyle':
                  'setHorizontalBorderChar': 'setDefaultHorizontalBorderChar'
                  'setCrossingChar': 'setDefaultCrossingChar'
```

But for this code example:

```php
        $tableStyle = new TableStyle();
        $tableStyle
            ->setCrossingChar(' ')
            ->setHorizontalBorderChar('<fg=magenta>-</>')
        ;
```

It only suggests this diff

```diff
--- Original
+++ New
@@ -38,7 +38,7 @@

         $tableStyle = new TableStyle();
         $tableStyle
-            ->setCrossingChar(' ')
+            ->setDefaultCrossingChar(' ')
             ->setHorizontalBorderChar('<fg=magenta>-</>')
         ;
    ----------- end diff -----------
```

I tried to track the bug down today but I had to give up at some point.
