### ISSUE TITLE
Yaml regex experiment

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#503]
Since more people asked about this, it deserves reopening

Before we though about using parsing/dumping/modifying ast of yaml #17

Maybe it would be enough to use regular instead.
https://www.google.cz/search?q=regex+replace+word+folowed+by+another+word&oq=regex+replace+word+folowed+by+another+word&aqs=chrome..69i57.15559j0j7&client=ms-android-google&sourceid=chrome-mobile&ie=UTF-8

"key:\s+old_subkey" to "key:\s+new_subkey"

**Comment by TomasVotruba** [comment]
- https://github.com/shopsys/shopsys/commit/c035785bccd6abbebbb4a0f1184a4a4e2857e25b#diff-b401dbbf5297ae59e7fbca6571583a14

- https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#security

### Main cases?

- try preg_replace... on first match stop
- turn to dummy rettors, nothing complex

```yaml
key:
	another_key: old_value

key:
	anothe_key: new_value
```

# 2

```yaml
key:
	old_key: value

key:
	new_key: value
```
