### ISSUE TITLE
Change config (and other non-php) files too

### ISSUE THREAD

**Issue by lulco** [rectorphp/rector#5282]
As we discussed on twitter, I am creating issue...

Since I live in Nette world I was focused on how to migrate configs of Nette applications (Neon files) 2.4 to new versions. I tried several approaches, which (maybe) will help you to do the right decision or at least they will show you what is not the right way:
1) Neon::decode -> Neon:encode
	pros:
		- changes on/off to true/false (because on/off are deprecated in 3.0)
 	cons:
 		- changed formatting (tabs instead of spaces)
		- adds numeric keys to anonymous services (`- Service1` is changed to `0: Service1`) - this is understandable since neon is just an array
		- ignores that class should be changed to factory - it is not its responsibility
		- ignores schema of extensions (for example: database › default › password should be string, so if your database password was 123, it will be unchanged)

2) Configurator + Compiler (idea)
Based on findings with approach 1) I was trying to build Container using Configurator + Compiler in while cycle and in each step I tried to fix one error (which was thrown by the Compiler). I didn't finish work on it.
	pros:
		- if it would work, it would be great self-correcting mechanism
	cons:
		- it would be extremely complicated and probably will not work anyway :)
			- we would need all config files, in same order as they are used in app
			- we have to clear cache after each change
		- it was slow

Approaches 1) and 2) are not generic for all frameworks and file types, so I went back to my very first choice: Regular expressions. I already use them when upgrading apps from Nette 2.4 to Nette 3.0 and they work just fine.
	pros:
		- they are generic (can be used also in another file types - latte, yaml, xml, twig, even in php for some "unrectorable" situations...)
		- I believe you can handle anything with good regex
		- it is already used in Rector with NonPhpFileClassRenamer
		- with --dry-run you can try it over and over again
	cons:
		- possible false positives
		- it is regex :) it is not so cool like the rest of Rector

After too many hours spend with this issue, I am convinced that replace strings in non-php files with regular expressions is the right and only possible way how to upgrade any application.

**Comment by Aerendir** [comment]
I don't understand why use regular expressions.

Nette has a decoder for neon files: https://github.com/nette/neon

Why would you use reg exes instead of a simple array get using the package from Nette?

**Comment by lulco** [comment]
@Aerendir Like I wrote, we need some generic solution. Nette::decode just create array from string. That is not bad, but we need to do some changes required by new versions of framework. Also there are some problems with formatting when we encode array back to string. See example below:

```
Original:
----------
# Global comment
parameters:
    simpleString: value
    simpleArray: [value1, value2]
    bulletPointsArray:
        - value1
        - value2
    booleanTrue: on # Parameter comment
    booleanFalse: off

services:
    service1:
        factory: Foo\Service1   # Service comment
    - Foo\Service2
    - Foo\Service3
    service4: Foo\Service4
---- END ---

New:
----------
parameters:
	simpleString: value
	simpleArray:
		- value1
		- value2

	bulletPointsArray:
		- value1
		- value2

	booleanTrue: true
	booleanFalse: false

services:
	service1:
		factory: Foo\Service1

	0: Foo\Service2
	1: Foo\Service3
	service4: Foo\Service4

---- END ---
```

- spaces are changed to tabs
- comments are removed
- simple array `[]` is changed to bullet points array `-`
- `on` / `off` is changed to `true` / `false` <--- this is the only thing we want
- anonymous services get numbers
- new line is added at the end <--- this is not so big deal
