### ISSUE TITLE
Resolve multiple items or one item configuration

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#548]
There are few rectors configured like this:

```yaml
services:
    NamespaceReplacerRector:
        $oldNamespace: 'OldNamespace'
        $newNamespace: 'NewNamespace'
```

and few like this:

```yaml
services:
    NamespaceReplacerRector:
        $oldToNewNamespace:
            'OldNamespace': 'NewNamespace'
```

Why is that WTF? Well, how would you extend it with another case?

```diff
 services:
     NamespaceReplacerRector:
         $oldNamespace: 'OldNamespace'
         $newNamespace: 'NewNamespace'
+
+    NamespaceReplacerRector:
+        $oldNamespace: 'AnotherOldNamespace'
+        $newNamespace: 'AnotherNewNamespace'
```

vs

```diff
 services:
     NamespaceReplacerRector:
         $oldToNewNamespace:
             'OldNamespace': 'NewNamespace'
+            'AnotherOldNamespace': 'AnotherNewNamespace'
```

The second has nicer UX and has less repetetive code (= less bugs, less risk of  error).

Current status is confusing and WTF for end users and lead to missplacing these cofings.

Analyze, think of one and use it

**Comment by vasilvestre** [comment]
I would like to help on this one but I don't see any rector having this behaviour.

**Comment by TomasVotruba** [comment]
Found it!

PropertyAssignToMethodCallRector

### Current style

```yaml
services:
    Rector\Rector\Assign\PropertyAssignToMethodCallRector:
        $types:
            - 'Rector\Tests\Rector\Assign\PropertyAssignToMethodCallRector\Source\ChoiceControl'
            - 'Rector\Tests\Rector\Assign\PropertyAssignToMethodCallRector\Source\MultiChoiceControl'
        $oldPropertyName: 'checkAllowedValues'
        $newMethodName: 'checkDefaultValue'
```

### Common style

```yaml
services:
    Rector\Rector\Assign\PropertyAssignToMethodCallRector:
        Rector\Tests\Rector\Assign\PropertyAssignToMethodCallRector\Source\ChoiceControl:
            checkAllowedValues: checkDefaultValue
        Rector\Tests\Rector\Assign\PropertyAssignToMethodCallRector\Source\MultiChoiceControl:
            checkAllowedValues: checkDefaultValue
```

**Comment by TomasVotruba** [comment]
## RenameClassConstantsUseToStringsRector

### Current style

```yml
services:
    Rector\Rector\Constant\RenameClassConstantsUseToStringsRector:
        $class: 'Nette\Configurator'
        $oldConstantToNewValue:
            'DEVELOPMENT': 'development'
            'PRODUCTION': 'production'
```

### Common style

```yml
services:
    Rector\Rector\Constant\RenameClassConstantsUseToStringsRector:
        Nette\Configurator:
            'DEVELOPMENT': 'development'
            'PRODUCTION': 'production'
```

**Comment by TomasVotruba** [comment]
## MethodCallToAnotherMethodCallWithArgumentsRector

### Current style

```yaml
services:
    Rector\Rector\MethodCall\MethodCallToAnotherMethodCallWithArgumentsRector:
        $serviceDefinitionClass: 'Rector\Tests\Rector\MethodCall\MethodCallToAnotherMethodCallWithArgumentsRector\Source\NetteServiceDefinition'
        $oldMethod: 'setInject'
        $newMethod: 'addTag'
        $newMethodArguments: ['inject']
```

**Comment by TomasVotruba** [comment]
## ProcessBuilderRector

### Current style

```yaml
services:
    Rector\Symfony\Rector\Process\ProcessBuilderInstanceRector:
        $processBuilderClass: 'Rector\Symfony\Tests\Rector\Process\ProcessBuilderInstanceRector\Source\ProcessBuilder'
```
