### ISSUE TITLE
Rectorizer 🤖

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector#5570]
# BREAKING News

I'm working on a public service downgrading code from PHP 8 as I don't have/know PHP 8.

![kép](https://user-images.githubusercontent.com/952007/108046873-6be29d80-7045-11eb-999c-343e8eb3a0ed.png)

https://github.com/szepeviktor/rectorize/actions?query=workflow%3ARectorize

**Comment by szepeviktor** [comment]
Result:

![kép](https://user-images.githubusercontent.com/952007/108047271-e3b0c800-7045-11eb-8894-bc4866db235d.png)

**Comment by szepeviktor** [comment]
If you open a PR you may edit rector config.

**Comment by TomasVotruba** [comment]
Cool news!

Could you show us how to use it here to build PHP 7.1 version of Rector?
https://github.com/rectorphp/rector/blob/master/.github/workflows/build_php71.yaml

**Comment by szepeviktor** [comment]
Fork https://github.com/szepeviktor/rectorize

Edit `rector.php` by adding
```php
        DowngradeSetList::PHP_80,
        DowngradeSetList::PHP_74,
        DowngradeSetList::PHP_73,
        DowngradeSetList::PHP_72,
```

Go to `https://github.com/FORK/rectorize/actions?query=workflow%3ARectorize`

Press <kbd>Runworkflow</kbd>

Enter https://github.com/rectorphp/rector.git and the necessary paths (which I do not know)

Download Actions artifacts.

Done!

**Comment by TomasVotruba** [comment]
We need it in CI, fully automated

**Comment by szepeviktor** [comment]
I see.

```yaml
      - name: "Clone and rectify project"
        run: |
          git clone "$URL" build/
          cd build/
          composer update --no-interaction --ignore-platform-reqs --prefer-dist
          composer require --no-interaction --ignore-platform-reqs --dev rector/rector-prefixed
          vendor/bin/rector process --config=../rector.php $PATHS
          tar -cf build.tar .

      - name: "Upload rectified source code"
        uses: "actions/upload-artifact@v2"
        with:
          name: "results"
          path: "build/build.tar"
          retention-days: 1
```

This is how it is done in my project:

1. get source code
2. install rector-prefixed
3. Run!
4. upload as Action artifacts
