### ISSUE TITLE
FunctionReplaceRector - rename of method changes spacing of args

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#624]
```yaml
# rector.yml
services:
    Rector\Rector\Function_\FunctionReplaceRector:
        $oldFunctionToNewFunction:
            define: 'Safe\define'
            substr: 'Safe\substr'
            class_implements: 'Safe\class_implements'
            sprintf: 'Safe\sprintf'

```

```diff
--- Original
+++ New
@@ -51,11 +51,7 @@
     protected function configure(): void
     {
         $this->setName(CommandNaming::classToName(self::class));
-        $this->setDescription(sprintf(
-            'Splits monorepo packages to standalone repositories as defined in "%s" section of "%s" config.',
-            'parameters > directories_to_repositories',
-            'monorepo-builder.yml'
-        ));
+        $this->setDescription(\Safe\sprintf('Splits monorepo packages to standalone repositories as defined in "%s" section of "%s" config.', 'parameters > directories_to_repositories', 'monorepo-builder.yml'));
     }
```
