### ISSUE TITLE
Delimiter issue on exclude_paths

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#632]
```yaml
parameters:
    exclude_paths:
        - '_files/BankAccountTest2.php'
```

![image](https://user-images.githubusercontent.com/924196/45831072-bdfd2880-bcfe-11e8-90d7-63886b25d951.png)

This should work
