### ISSUE TITLE
Ideas to use abstract class replacer in config way

### ISSUE THREAD

**Issue by TomasVotruba** [RectorPHP/Rector#69]
Faster to bootstrap:

```yaml
# symfony33.yml
rectors:
    ClassReplacer:
        OldClass: NewClass
```

It would also make change more transparent and easy to scale - adding new class is now easy.

It's not worth writing custom class and tests, since it only uses `AbstractClassReplacerRector` over and over again.

What do you think @grogy?

### Todo

- [ ] document in docs: *How to write Rectors* → *Class or method replacement in config*
