### ISSUE TITLE
ClassPropertyAssignToConstructorPromotionRector renames constructor arguments

### ISSUE THREAD

**Issue by niji-mneute** [rectorphp/rector#6981]
# Bug Report

| Subject        | Details        |
| :------------- | :------------|
| Rector version | v0.12.15  |

When using the ClassPropertyAssignToConstructorPromotionRector rule to promote properties, Rector renames the constructor parameters if they don't have the same name than the property, which causes problems with Symfony autowiring

## Minimal PHP Code Causing Issue

Let's suppose we configured Symfony this way :
```yaml
services:
    _defaults:
        bind:
            string $appEnv: '%kernel.environment%'
```
Then the autowiring expects a parameter named this way : `string $appEnv`, and Rector might change it.

https://getrector.org/demo/1ec84129-0fc1-6e8e-bac4-45f8d38f6382

## Expected Behaviour

No modifications done in the original code.
