### ISSUE TITLE
AnnotatedPropertyInjectToConstructorInjectionRector cannot handle imported aliased annotations

### ISSUE THREAD

**Issue by bendavies** [rectorphp/rector#700]
Hi there,

Consider this example, which is directly pulled from the JMSDIExtra bundle docs:
```php
<?php

use JMS\DiExtraBundle\Annotation as DI;

class Controller
{
    /** @DI\Inject("doctrine.orm.entity_manager") */
    private $em;

    /** @DI\Inject("session") */
    private $session;
}
```

It seems `AnnotatedPropertyInjectToConstructorInjectionRector` can't handle this case. I would expect this to work:

```yaml
services:
  Rector\Rector\Architecture\DependencyInjection\AnnotatedPropertyInjectToConstructorInjectionRector:
    $annotation: JMS\DiExtraBundle\Annotation\Inject
```

Is there a way to make the above example work, without reworking all the injection annotations?

Thanks!
