### ISSUE TITLE
ExceptionHandlerTypehintRector fails on nullable parameters

### ISSUE THREAD

**Issue by buffcode** [rectorphp/rector#789]
Whenever a nullable parameter is used, the `ExceptionHandlerTypehintRector` fails to process the file.

```yml
# rector.yml
services:
  Rector\Php\Rector\FunctionLike\ExceptionHandlerTypehintRector:
    class: Rector\Php\Rector\FunctionLike\ExceptionHandlerTypehintRector
```

```php
// example.php
class Example {
    public function foo(?bool $bar) {}
}
```
produces
> PHP Recoverable fatal error:  Object of class PhpParser\Node\NullableType could not be converted to string in vendor\rector\rector\packages\Php\src\Rector\FunctionLike\ExceptionHandlerTypehintRector.php on line 59
