### ISSUE TITLE
Add levels on rector.yml

### ISSUE THREAD

**Issue by Soullivaneuh** [rectorphp/rector#799]
It looks to be the only missing thing from the configuration file.

Something like:

```yaml
parameters:
    levels:
        - symfony40
        - php73
```
