### ISSUE TITLE
Show in debug how long a rule takes something like SlowRuleLog maybe

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#8043]
# Feature Request

One of my projects is getting bigger and bigger and I need to increase the `rector->parallel()` configuration to get it run inside our gitlab CI runner.

Currently to run it in the CI I have to use:

```php
$rectorConfig->parallel(480);
```

On `240` it did already run into timeouts and so we doubled it. Default is 120 seconds.

I think it would be nice if `--debug` maybe shows also which rules did take the most time to maybe check a specific rule if it can be optimized.

**Comment by staabm** [comment]
This might be helpful to debug slow projects

https://staabm.github.io/2023/05/10/how-to-debug-slow-rector-projects.html

**Comment by alexander-schranz** [comment]
I don't see any time outputted by `--debug -vvv` maybe something which was changed in 0.17 ? And so the outputted of your script is seems to stay empty:

```bash
Slowest files

```

**Comment by alexander-schranz** [comment]
Thx I currently can not reproduce my timeout issue locally (MacOS brew PHP 8.1) but on CI I still run into timeouts:

PS: I did put your script into copy&paste able oneliner to use it locally and in my CI script:

```yaml
Rector Test:
    stage: Test
    needs:
        - Install # composer install
    image: php:8.1-cli
    script:
        - php vendor/bin/rector -vvv --debug --no-diffs | tee var/rector-slow-log.log
        # see: https://staabm.github.io/2023/05/10/how-to-debug-slow-rector-projects.html
        - |
           php -r 'declare(strict_types=1); $log = new SplFileObject("var/rector-slow-log.log"); $logs = []; $file = null; while (! $log->eof()) { $line = trim($log->fgets()); if ($line === \'\') { continue; } if (str_starts_with($line, \'[file]\')) { $file = $line; continue; } if ($file === null) { continue; } if (preg_match(\'/took (?<seconds>[\\d.]+) s/\', $line, $matches) === 1) { $accu = 0.0; if (array_key_exists($file, $logs)) { $accu = $logs[$file][0]; } $logs[$file] = [$accu + ((float) $matches[\'seconds\']), $file]; $file = null; } } usort($logs, fn(array $left, array $right) => $right[0] <=> $left[0]); $logs = array_slice($logs, 0, 100); echo "Slowest files" . PHP_EOL; foreach ($logs as $log) { echo sprintf("%.2f seconds: %s", $log[0], $log[1]) . PHP_EOL; }'
    artifacts:
        name: rector-slow-log
        expire_in: 72 hours
        when: always
        paths:
            - var/rector-slow-log.log
 ```
