### ISSUE TITLE
Provide a --cache-directory cli option 

### ISSUE THREAD

**Issue by soullivaneuh** [rectorphp/rector#8335]
# Feature Request

Currently, the file cache directory has to be set on the project local configuration like so:

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->cacheClass(FileCacheStorage::class);
    $rectorConfig->cacheDirectory('./var/cache/rector');
};
```

I am working on a [project gathering linters/fixers onto CI jobs](https://gitlab.com/ss-open/ci/recipes), and I would like to integrate PHPStan.

This way of configuration is less convenient for me because I don't have the possibility to configure the files cache directory to a special path I use for saving unless telling the user to do it on its project configuration.

If the tool provide a `--cache-directory` option, it would make the implementation easier an less intrusive. Maybe something like that:

```yaml
lint:rectorphp
  script:
    - composer exec rector -- --dry-run --cache-mode=file --cache-directory=${CI_CACHE_PATH?}/rector
  cache:
    when: always
    paths:
      - ${CI_CACHE_PATH}
```

Here is an another sample of what I mean with PHPCodeSniffer: https://gitlab.com/ss-open/ci/recipes/-/blob/ca9870de82a7d7b858332426e28e4f62fe406c1a/stages/lint/php-code-sniffer/.gitlab-ci.yml#L13
