### ISSUE TITLE
[PHP] Add yield <=> array and array <=> yield by type and method mask

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#925]
## `array` → `yield`

```yaml
services:
    ArrayToYieldRector:
        TestCase:
            - provide*
            - dataProvider*
```

```diff
 public function provide()
 {
-    return [
-        ['item']
-    ];
+    yield ['item'];
 }
`` 

Based on https://github.com/rectorphp/rector/blob/9db613e92ee8c2f5f390937d856a25116b9b1071/packages/PHPUnit/src/Rector/ArrayToYieldDataProviderRector.php

---

## `yield` → `array`

```yaml
# rector.yml
services:
    YieldToArrayRector:
        EventSubscriber:
            - getSubscribedEvents
```

```diff
 public function provide()
 {
-    yield ['item'];
+    return [
+        ['item']
+    ];
 }
```
