### ISSUE TITLE
[PHP] Use constants over strings

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#930]
Inspiration https://github.com/goetas/twital/commit/97b55e0090705e4a589246ee3e2ec71b8fbd20c8

```yaml
services:
    StringsToConstantsRector:
          ConsoleEvents: ~
```
