### ISSUE TITLE
Idea - NewToFactoryRector

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#981]
Please @TomasVotruba feedback needed:

Before:
```php
public function xyz() {
    $a = new MyClass();
}
```

After:
```php
/** @var MyClassFactory */
private $myClassFactory;

public function xyz() {
    $a = $this->myClassFactory->createMyClass();
}
```

I am not sure about the config. We need to configure:  
1) Instance class
2) Factory class
3) Property visibility? Or set it private by default?
4) Property name

Can it works like this:
```yaml
services:
  MyFactoryRectorName:
    MyClass: # 1) instance class to get replaced with factory call
      factoryClass: MyClassFactory # 2) factory class
      factoryPropertyName: $myClassFactory # 3) property name
      factoryPropertyVisibility: private # 4) property visibility
```

What do you think? Will it be possible to access these config options in rector class?

**Comment by TomasVotruba** [comment]
Agreed. *After* should contain constructor as well.

```yaml
services:
    NewObjectToFactoryCreateRector:
        # 1) instance class to get replaced with factory call
        Object: ['FactoryClass', 'method'] # 2) factory class + factory method
```

This configs respects current conventions in configs.

3) name is resolve by type convention, e.g. `Type` => `$type`
4) is not needed, private is by default since it's new property
