### ISSUE TITLE
Cannot declare class  - Level symfony 34 throws an error on 2.8 Symfony Code

### ISSUE THREAD

**Issue by theovach** [rectorphp/rector#985]
When I try to dry run with level symfony 3.4 on 2.8 code I get every time:
PHP v7.2.14
rector v0.3.37
PHP Fatal error:  Cannot declare class Symfony\Component\HttpFoundation\ParameterBag, because the name is already in use in /var/www/html/adb_webapp/var/bootstrap.php.cache on line 6

**Comment by TomasVotruba** [comment]
How did you install Rector?

What exact command do you run?

This might be due to conflicting version of Symfony. Rector uses Symfony 3.4/4.2, your app probably older.

**Comment by theovach** [comment]
Installed via
composer require rector/rector --dev
Symfony is 3.4.21

**Comment by TomasVotruba** [comment]
What exact Rector command do you run?

**Comment by theovach** [comment]
> What exact Rector command do you run?
In the symfony project folder 

./rector process {SYMFONY_PROJECT_FOLDER}/src --level symfony34 --dry-run

**Comment by TomasVotruba** [comment]
This issues is quite common. It's caused by the fact Rector loads Symfony coce from your project and from itself - twice.

The only solution in the future will be prefixed PHAR. It's being worked on in https://github.com/rectorphp/compiler
Any help there would make it sooner.

**Comment by TomasVotruba** [comment]
Duplicated issue to better described: https://github.com/rectorphp/rector/issues/177

**Comment by TomasVotruba** [comment]
There is a solution now: https://github.com/rectorphp/rector-prefixed

**Comment by tuc0w** [comment]
@TomasVotruba I am using the latest prefixed version (0.7.2) in a Symfony 3.4 project and I am running the two sets 'php72' and 'symfony40'.

`Fatal error: Cannot declare class XXXX\YYYYBundle\Entity\Xyz, because the name is already in use in /vagrant/yyyy/src/XXXX/YYYYBundle/Entity/Xyz.php on line 14`

```yaml
# rector.yaml
parameters:
    auto_import_names: true
    autoload_paths:
        - 'src/zzz/DrunkenWizardBundle'
        - 'src/zzz/OfficeOpenXmlBundle'
    exclude_paths:
        - '/src/zzz/OfficeOpenXmlBundle/Classes'
    paths:
        - 'src'
    sets:
        - 'php72'
        - 'symfony40'
```

Any idea why it is still happening?
