### ISSUE TITLE
ClassConstantReplacerRector - make it possible to replace with constant from other class

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector#999]
Now it is possible only to replace constant with different constant on same class. 

Let's make it possible to replace with constant from different class.

```yaml
services:
    Rector\Rector\Constant\ClassConstantReplacerRector:
        SomeClass:
            OLD_CONSTANT: NewClass::NEW_CONSTANT
```

Before:
```php
SomeClass::OLD_CONSTANT
```

After:
```php
NewClass::NEW_CONSTANT
```
